README.md, lib/config.js, lib/response.js, public/views/foot.ejs, public/views/header.ejs, public/views/index.ejs
First of all, 0.4 is a great release, and the single database dependency now simplifies everything a lot.
2 Points I fixed:
- Login button and message on history page only shows when we have a login method enabled
- Dropbox and Google Drive export only available, when configured
=> Hide unused UI elements

app.js, config.json, lib/auth.js, lib/config.js, lib/models/user.js, lib/response.js, package.json, public/views/signin-modal.ejs
Commit List:
* Add necessary dependency.
* Add baseURL parameter for self-hosted GitLab
* Add necessary require.
* Add block for GitLab auth.
* Fix typo
* Update font-awesome dependency for GitLab icon.
* Use a color closer to GitLab orange.
* More direct TODO
Focus solely on authentication, saving/opening `snippets` not addressed.
=> Extend to support GitLab Authentication

.editorconfig, .eslintrc
Prevent our favorite editor from accidentally trimming trailing whitespace 😓 .
* Create `.editorconfig`. Current indentation is using space and width 4.
* Generate eslint config
=> Sample editorconfig & eslint

public/views/foot.ejs, public/views/head.ejs, public/views/html.hbs, public/views/index.ejs, public/views/pretty.ejs, public/views/slide.ejs
As I discussed with @jackycute earlier, this PR will
1. force enable https rather than just use protocol relative url for the security and http/2.0(and spdy) feature
2. try to use single cdn, currently CDNJS to maximize the benefits from http/2.0(and spdy) - multiplex the connections
3. enable SRI - subresource integrity - for security enhancement
=> Use CDNJS by default with https and SRI support

README.md, lib/config.js, lib/realtime.js, lib/response.js, public/views/body.ejs, public/views/index.ejs
Commit 5c7eb483198d0d92dc88c7a7c25cca5c23eb5cf2 added the configuration value `allowanonmyous` and the environment variable `HMD_ALLOW_ANONMYOUS`. The word *anonymous* is misspelled consistently throughout the code, which is fixed by this pull request.
Having these names misspelled can lead to unexpected behavior for users who do not copy/paste the variable names, so supporting the correctly spelled names should be desirable.
In its current stage, the pull request does not recognize the misspelled names introduced in 5c7eb483198d0d92dc88c7a7c25cca5c23eb5cf2. I think this is a very minor breaking change, but if desired, I could add support for the misspelled names as a fallback.
=> Fixed typo: anonmyous

app.js
Fixed an issue where URLs are not handled correctly when uploading images to local filesystem.
For example, if the URL of your hackmd server is https://example.com/, the markdown inserted at the time of image drop will be in a state where the slash is insufficient as follows.
```
```
This is due to using the path.join of Node.js, and solving it by using the url.resolve instead.
```
var serverUrl = 'https://example.com/'
var imagePath = 'uploads/upload_912f83d804cb0219ae628d1062d4f8f0.jpg'
path.join(serverUrl, imagePath)
// Returns: 'https:/example.com/uploads/upload_912f83d804cb0219ae628d1062d4f8f0.jpg'
url.resolve(serverUrl, imagePath)
// Returns: 'https://example.com/uploads/upload_912f83d804cb0219ae628d1062d4f8f0.jpg'
```
=> Fix URL concatenation when uploading images to local filesystem

README.md, lib/config.js, public/views/signin-modal.ejs
This is the first PR to complete the additional steps outlined in the last LDAP-related PR https://github.com/hackmdio/hackmd/pull/279
=> Allow displaying LDAP provider name on sign-in modal

README.md, app.js, lib/config.js, lib/response.js, public/views/signin-modal.ejs
A small contribution to solve some "paper cut issues" ;)
#297
=> Add `allowemailregister` option

app.js
SIGTERM is now handled properly and performs a graceful shutdown the same way SIGINT does.
Before, SIGTERM couldn't kill the process, which eventually caused the operating system or dockerd to issue a SIGKILL to terminate the server unconditionally.
=> Handle SIGTERM the same way SIGINT is handled

bin/setup
Fail the script if a command inside it fails to prevent a install with exitcode 0 even when commands in it are failing.
=> Add fail fast option

public/js/cover.js, public/js/extra.js, public/js/index.js
In FileSaver.js, BOM is toggleable.
(see eligrey/FileSaver.js@631047d72f4e89fab6059203ca71eb064a0bb031)
=> Removed UTF-8 BOM in download function

README.md
`make` and `gcc` are required in [node-gyp](https://www.npmjs.com/package/node-gyp).
Without these packages, `bin/setup` ,which is instructed in Get started will fail.
=> Add additional comment about Prerequisite to README

app.js
When using `filesystem` backend in `imageUploadType` and `config.serverurl` is set, path to uploaded image is wrong.
=> Fix image path problem when using filesystem backend

README.md, lib/config.js, lib/models/note.js
Use `defaultpermission`(config.json) or `HMD_DEFAULT_PERMISSION`(environment value) to set default permission of newly created note.
=> Add default permission config

.editorconfig, package.json, public/js/index.js, public/js/lib/editor/index.js, public/js/lib/editor/ui-elements.js, public/js/lib/editor/utils.js
- Extract codemirror instance out of `public/js/index.js` to `public/js/lib/editor/index.js`
- Extract common jquery ui node out of `public/js/index` to `public/js/lib/editor/ui-elements.js`
- Extract `wrapTextWith` to `public/js/lib/editor/utils.js`
- Change `.editorconfig` to meet our new standardjs indent favor
- Patch more global variable to standardjs global variable list
=> Extract CodeMirror instance

.editorconfig, public/js/extra.js, public/js/index.js, public/js/lib/editor/config.js, public/js/lib/editor/index.js, public/views/statusbar.html
- Seperate `line:column` and `selection` event binding
- Implement multiple event listener on the same CM event
```js
const editor = new Editor()
editor.on('cm-event', function() { console.log('first function 1') })
editor.on('cm-event', function() { console.log('first function 2') })
```
- Editor class maintain an array of functions internally, call each one on CM event sequentially
- Move `addStatusbar` method into editor class, since it's component of editor
- Drop global ui referencing in `extra.js`
- Minor coding fixes
- Create a editor config class (`public/js/lib/editor/config.js`), just a simple object store that can be shared across classes. 
```js
const config = require('./lib/editor/config')
config.abc = 'xyz'
```
=> Refactor editor cont.

.travis.yml
Two reasons here:
1) Ubuntu Precise is reaching EOL, though Travis CI may take care of it.
we still can move to Trusty earlier as I didn't see any dependency of
Precise here.
2) g++4.8 is built-in in Travis CI's Ubuntu Trusty environment, which
means we don't need to spend time on adding ppa repository, apt update
and apt install, could save time on the CI.
=> Move to Ubuntu Trusty on Travis CI and remove apt add-on

app.json, bin/heroku
- Remove `postdeploy` section in heroku `app.json`.  For a clean application, there is no need to run sequelize migration.
- Remove `npm install` from heroku script. Heroku detects `yarn.lock` automatically and install package for us.
=> Fix heroku deployment

app.js, lib/utils.js
As discussed in the issue https://github.com/hackmdio/hackmd/issues/435, when an image is uploaded to S3, no Content-Type is set. When you try to open the image in a new tab, it starts to download the image.
With this PR, I have added a simple functionality that adds the Content-Type to the image, so the images are processed as images instead of stream objects.
It also helps to create markdowns in Hackmd and use them into Github repos showing the images correctly.
=> Image Upload to S3 - ContentType not set

app.json
**For existing heroku users, remove `HMD_PORT` from your heroku app setting.**
Hackmd choose `HMD_PORT` over `PORT` value after #421. This caused heroku application won't start correctly. So just removed it.
> error: uncaughtException: listen EACCES 0.0.0.0:80
=> Fix error: uncaughtException: listen EACCES 0.0.0.0:80 on heroku

package.json
Use `--bail` option to exit with a non-zero code when `webpack` fails instead ending successfully.
It also provides more useful debug output on fail.
=> Use non-zero exit codes when build fails

lib/web/imageRouter.js
Fix Amazon S3 endpoint URL in us-east-1.
http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region
* us-east-1(not contain `-${region}`):
```
s3.amazonaws.com
```
* other regions:
```
s3-${region}.amazonaws.com
```
=> fix s3 us-east-1 region endpoint

locales/de.json
In this way the button makes IMO much more sense:
rather than
CC @janniklorenz
=> Translate "revert" to "Zurücksetzen" in German

package.json
Using the "github:..." form to declare a dependency in package.json
makes npm attempt to install the package using an ssh clone rather than
an https clone. Some deployment environments may not allow ssh access
to external servers which will prevent the clones from succeeding. Using
the "git+https://..." form will clone the same repo from GitHub without
requiring ssh connectivity.
=> Use git URLs in package.json

README.md, docs/guides/s3-image-upload.md
Documentation added in aaf034b on Nov 17th 2016 says the S3 bucket can be specified with `s3.bucket`, but commit c8bcc4c (#285) on Dec 18th 2016 used `s3bucket`. Instead of fixing the code (#552) to match the documentation this commit changes just the documentation so that existing configurations are not broken. Also, the `s3` object is passed as is to `AWS.S3()`, which does not know the option `bucket` (but silently ignores it in my test).
http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#constructor-property
Following the old documentation leads to this exception:
2017-09-23T09:42:38.079Z - error:  MissingRequiredParameter: Missing required key 'Bucket' in params
at ParamValidator.fail (/srv/hackmd/hackmd/node_modules/aws-sdk/lib/param_validator.js:50:37)
at …
=> Correct documentation of S3 bucket

webpack.production.js
Changes:
- Bumps the max line length from default value of 30000
Fixes: #388
=> Updates default max_line_len in uglifyjs

.travis.yml
=> Remove duplicated nodejs version in .travis.yml

lib/config/environment.js
`HMD_URL_ADDPORT` wasn't parsed correctly and caused broken pages by adding the port number no matter if it's `true` or `false`.
=> Fix missing boolean setting for HMD_URL_ADDPORT

README.md, app.js, app.json, config.json.example, lib/config/default.js, lib/config/environment.js
This PR allows users to influence HSTS behaviour as outlined in #584. To achieve that, it adds some new configuration settings to `config.json.example` (and `lib/config/default.js`) under the `hsts` key:
````json
"hsts": {
"enable": "true",
"maxAgeSeconds": "31536000",
"includeSubdomains": "true",
"preload": "true"
}
````
These defaults should match the currently hard-coded values exactly. The maximum age is provided in seconds to improve readability while still maintaining reasonable configurability. The new options are also represented in `README.md` and `app.json`. For `README.md`, I followed the pattern of existing documentation and provided all the settings as one row, with a JSON example.
Further, this PR adds environment variables for configuring aforementioned options: …
=> Make HSTS Behaviour Configurable (Fixes #584)

public/js/extra.js
=> Fix markdown-it gist plugin code closing tag

lib/web/auth/ldap/index.js
Try to fix #432
After checking multiple RFCs and references `uid` and `sAMAccountName` seem to be the most commonly used fields.
`uidNumber` is a POSIX reference for the uid that is used when people log in to a Unix host. This should not be used for HackMD.
I don't think that it's a perfect solution. My first try was to add a settings field for it, but it seems to overcomplicate things and is unnecessary long.
I'll test this later. Hopefully during this weekend.
=> Fix LDAP problem about missing uidNumber

public/css/slide.css, public/views/slide.ejs
For #598, I externalised some inline styles under the impression that I could fix them all. I quickly realised that some are generated dynamically by JS or using template variables, so the effort is pointless. For all these selectors I did a code search to see if they'd clash with any other HTML, so *technically* these changes shouldn't have any side effects.
Anyways, here are the changes the the one file I did do it for. Take it or leave it, just putting this here in case it's helpful.
=> Externalise some trivial inline styles from slide.ejs

README.md
I reorganized the docker section a little bit since we have now the new container build environment using TravisCI.
Feel free to comment and improve! I would really appreciate native English speakers review of grammar and language usage but of course, all others are welcome to improve it as well! :heart:
=> Extend docker section in README

public/views/hackmd/header.ejs
Right now, the error page breaks because the `allowpdfexport` is not checked for existence.
=> Fix allowpdfexport handling on error page

public/js/render.js
Fixes #626 
I don't think there are many people using this option, so it can be safely removed.
=> Prevent XSS vulnerbility by srcdoc in iframe

README.md, config.json.example, lib/config/environment.js, lib/config/utils.js
Hello!
The full context of this PR can be found in issue #649, but to reiterate:
- The [passport-ldapauth](https://github.com/vesse/passport-ldapauth#configure-strategy) strategy's `searchAttributes` field takes an array.
- Our `HMD_LDAP_SEARCHATTRIBUTES` environment variable is interpretted as a string.
This PR instead interprets `HMD_LDAP_SEARCHATTRIBUTES` as a comma-separated array.
Also to note, I've added a `toArrayConfig` function to match the `toBooleanConfig` function found in `lib/config/utils.js` and converted the existing array environment variables to also use it.
It defaults to comma `,` separators and falls back to `undefined`, but this can be overridden per-variable.
The existing pipe `|` separated variables use this override for compatibility with existing setups:
- …
=> Parse env var `HMD_LDAP_SEARCHATTRIBUTES` as a comma-separated array

public/js/lib/editor/index.js
The tooltips didn't particularly make sense witht their wording before.
=> Correcting grammatical errors related to the document char count tooltip

README.md, config.json.example, lib/config/default.js, lib/config/environment.js, lib/web/auth/ldap/index.js
This determines which ldap field is used as the username on
HackMD. By default, the "id" is used as username, too. The id
is taken from the fields `uidNumber`, `uid` or
`sAMAccountName`. To give the user more flexibility, they can
now choose the field used for the username instead.
---
Context: I want to use HackMD in an LDAP environment, where the ldap field chosen for the user id is just a number. Seeing a number on the top right in HackMD is a bit ugly. So with this PR, I can choose which ldap field is used as username.
I hope this PR is fine. I don't have any experience in JS. I tested this patch with my ldap server and everything runs fine.
=> Add setting `ldap.usernameField`

locales/en.json, public/css/extra.css, public/css/github-extract.css, public/css/index.css, public/css/markdown.css, public/js/index.js, public/js/lib/appState.js, public/js/lib/editor/ui-elements.js, public/views/hackmd/header.ejs
I've implemented a dark theme feature. 
Thought to share it. 
Also, feedbacks of any kind are highly appreciated.
=> Implemented dark theme.

public/js/extra.js
id shouldn’t be converted to lowercase since id attribute is case sensitive
=> Fix anchor id to keep uppercase characters

lib/migrations/20171009121200-longtext-for-mysql.js, lib/models/note.js, lib/models/revision.js
This fixes #521 by making the `TEXT` column larger for MySQL / MariaDB. In PostgreSQL, `TEXT` is already very large, but on MySQL this is just ~64KiB long.
Includes a migration to enable this. This should not change anything on PostgreSQL, as Sequelize maps the field to `TEXT` on that platorm anyway.
Can somebody please confirm that this does not break (or in fact change) PostgreSQL? You'll need to run 
`node_modules/.bin/sequelize db:migrate` (perhaps with your environment)
=> converting all content fields to MEDIUMTEXT (affects MySQL only)

lib/config/defaultSSL.js, lib/config/index.js
#634 Thanks for your suggestion I finally split two pull request.
@SISheogorath
=> Fix sslcapath bug

lib/config/index.js
This de-duplicates the version number from the code and focuses on the version from `package.json`
=> Load version from package.json

lib/response.js, lib/web/noteRouter.js, lib/web/utils.js
This allows to specify initial content while creating a new note.
=> Allow posting new note with content

lib/config/default.js, lib/config/environment.js, lib/web/imageRouter.js, package.json
I know of the existence of #345 but it hasn't been updated in a while and there have been some changes on master that make that pull request useless.
I tried using our minio instance as if it were and Amazon S3 endpoint ( adding a slight change to support a different endpoint than the defaults from Amazon) but the aws-sdk refused to work ( for some reason it still contacts Amazon to verify the credentials).
Thus, I ended up opting for adding full support for minio using https://github.com/minio/minio-js
I also noticed that there is an s3bucket config option which somehow I believe it belongs to the s3 section but I didn't dare to change that.
=> Add support for minio

lib/config/environment.js
The parseInt breaks the config readon from `config.json` because it results in `NaN` instead of leaving it undefined.
=> Fix broken port config

README.md, docs/guides/minio-image-upload.md, docs/guides/s3-image-upload.md, lib/config/default.js, lib/config/environment.js, lib/config/index.js, lib/web/imageRouter.js
This removes the only camel cased option of the config options
**we** added to the config.json.
In auth provider's config parts are a lot of camel cased options
provided. We shouldn't touch them to keep them as similar as
possible to the examples.
Fixes #315
=> Remove camel case from `imageuploadtype` in config

lib/web/auth/index.js
Since we added user management it's possible to get non-existent users
which can cause a crash of the Backend server.
=> Fix uncaught exception for non-existent user

lib/realtime.js, public/js/index.js
I've been running with this commit (based on d1d6d5810b12645ddb02275ce0c2498b2189a8a0) for quite some time and it didn't cause any problems so far (had some users with "paranoid" browser settings which removed the referer).
When this change gets deployed all users need to reload, as otherwise the javascript running in the browser doesn't send the `noteid` query parameter while the server is expecting it.
=> don't require referer to find note id in socket.io connections (fixes #623)

app.js
This commit adds a referrer policy to all requests.
The usage of `same-origin` allows HackMD to still interpret all requests
and this way not break anything. But it prevents 3rd party scripts,
pictures and more to get informations that may lead to not secured note.
It has to be mentioned that this maybe breaks some features of the
Google Analytics embedding. This has to be tested.
Fixes #724
=> Add referrer policy

lib/response.js
refer to: https://github.com/hackmdio/hackmd/issues/727
=> Fix to show 500 message when got error in parseNoteId

public/js/lib/editor/index.js
This change allows all input modes of codemirror to use the information
from an input esc-key and make this way vim and sublime more
functional. To prevent this change from breaking the return from the
fullscreen mode, it catches the esc-key in this case. Hopefully this is
an acceptable solution.
As before the vim-mode is handled different in fulltext-mode as it is
esc-key heavy.
---
We should either fix or remove the fulltext mode as it's probably impossible to leave it right now in `vim` mode.
Fixes #738
=> Allow the usage of the esc-key by codemirror

public/css/markdown.css, public/js/render.js
HTML5 provides a wide feature set of useful elements. Since Markdown
usually supports HTML it should be able to use these HTML5 tags as well.
As they were requested by some users and they where checked for being
safe, whitelisting them isn't a problem. To make the experience the same
as on GitHub when it comes to the basic look and feel of the rendered
markdown, some CSS was added to make the summary and the details tag
look like on GitHub.
---
Fixes #671
=> Extend HTML5 support by whitelisting various tags

public/css/markdown.css, public/js/render.js
As https://github.com/hackmdio/hackmd/pull/740 mentioned
This PR add support of `rp` and allow `open` attribute of `details` tag.
Update styles for `details`, `summary` and `figure` tags.
=> Support more html5 tags and styles

README.md, config.json.example, lib/config/default.js, lib/config/environment.js, lib/web/auth/ldap/index.js
In our environment we don't have `uid` set on users. This leads to all users share the same profile called `LDAP-undefined`.
This fixes this under the assumption that usernames are unique anyways.
=> Use ldap.usernameField over hardcoded uid fields

README.md, config.json.example, lib/config/default.js, lib/config/environment.js
=> Remove unused LDAP option `tokenSecret`

package.json, webpackBaseConfig.js
This is my attempt to fix #715.
After removing the `engine.io-client@^1.8.2` dependency as @stbuehler suggested, `raphael` needed some convincing to still find `eve`.
In my (admittedly limited) testing, HackMD now works well, even with `"usecdn": false`.
=> Remove engine.io-client dependency

lib/web/auth/ldap/index.js
When a user has multiple email addresses in LDAP, the returned value is already and `Array`, re-wrapping causes the gravatar lookup to use the inner array of emails and failing to present the proper gravatar of the user.
=> Multiple emails from LDAP are already an Array

README.md, lib/config/default.js, lib/config/environment.js, lib/csp.js
This option is needed as it's currently not possible to add an report
URI by the directives array. This option also allows to get CSP reports
not only on docker based setup but also on our heroku instances.
Improves CSP support #594
=> Add config option for report URI in CSP

lib/config/environment.js, lib/config/utils.js
As minio causes various problem if you configure it using environment
variables and leave the port setting out, which will evaluate to NaN,
this change should fix this in a clean way for this time and helps to
support numbers in general in future.
Fixes #767
=> Add helper function to fix number problems

lib/migrations/20180306150303-fix-enum.js
Potential fix for #752 
Needs some testing on Postgres as well as MySQL.
=> Add missing migration for permissions

lib/history.js, lib/models/note.js, lib/realtime.js, lib/response.js, package.json, public/js/history.js, public/js/utils.js
=> Fix to use url-safe base64 in note url

lib/web/auth/ldap/index.js
This check is needed at there are tons of LDAP implementations out there
and none has at least one guaranteed unique field. As we currently check
three fields and added an option to select one yourself, it's still not
said that any of these fields is set. This will now create an error
and fail the authentication instead of letting people may get access to
other people's notes which are stored under a this way deterministic
wrong userid named `LDAP-undefined`.
Fixes #764 
@fooker would you like to review and test this?
=> Add check for undefined UUID

public/js/index.js
Right now the night mode is possible to set by a toggle in the menu bar
but needs to be re-enabled on every document switch, reload, etc.. This
is super annoying so we should keep this state in local storage or a cookie.
=> Persist nightmode so we can re-enable it on reload

public/js/index.js
The night mode toggle doesn't get the right state after restore from
local storage. This results in the need to toggle twice to disable night
mode.
This patch adds the needed class so the `toggleNightMode` function gets
the right state on execution.
=> Fix night mode button after restore

lib/csp.js
Adding mediaSrc to CSP so video and audio files can be embedded without
problems.
From a security perspective it should be fine to load audio and video
data without introducing a high security issue. Only from a privacy
perspective it allows another way to track users if there are data
embedded. But it doesn't introduce any new attack vector as pictures are
also allowed from everywhere.
=> Allow embedding of video and audio tags

lib/config/defaultSSL.js, lib/config/index.js
After discovering some issues with the usage of the old config variables, these fixes should correct the missing pieces.
sslCAPath should be set correctly now
And all legacy configs set to false and all default configs set to true should also be overwritten now.
=> Fix some issues with legacy config compatiblity

lib/config/default.js, lib/config/index.js
The session secret is used to sign and authenticate the session cookie
and this way very important for the authentication process.
By default the session secret is set to `secret` and never changes. This
commit will add a generator for a dynamic session secret if it stays
unchanges.
It prevents session hijacking this way and will warn the user about
the missing secret.
This also implies that on a restart without configured session secret
will log out all users. While it may seems annoying, it's for the users
best.
=> Automatically generate a session secret if default is used

README.md, app.json, lib/config/environment.js
Currently the session secret can only be set by config.json or docker
secrets. This creates a problem on Heroku hosted instances that can not
set a session secret.
Since we automatically generate them on startup this results in an
logout of all users on every config change in Heroku.
=> Add session data to env vars

config.json.example, lib/config/default.js, lib/csp.js, lib/response.js, public/views/shared/disqus.ejs, public/views/shared/ga.ejs
This commit should fix existing problems with Disqus and Google
Analytics enabled in the meta-yaml section of a note.
Before this commit they were blocked by the strict CSP. It's still
possible to disable the added directives using `addDisqus` and
`addGoogleAnalytics` in the `csp` config section.
They are enabled by default to prevent breaking changes.
--- 
**GA policy is still untested**
/cc @xxyy
=> Fix CSP for disqus and Google Analytics

public/css/index.css, public/css/markdown.css
Night mode provides a generally, dark interface. This fix provides the
needed CSS to also turn modal and panels into night mode design as well.
This mainly effects the help modal.
=> Fix modal and panel colors in night mode

locales/de.json, locales/en.json, locales/zh-CN.json, locales/zh-TW.json, public/views/shared/help-modal.ejs
As an active part of the community prefers Matrix.org over Gitter, we
should link Matrix.org as a place to meet us.
As the matrix and gitter channels are interconnected. We don't loose any
message if a person decides to go for one or another.
We use an more universal way of translation to make it easier to provide
a link to various platforms.
=> Add matrix.org / Riot link

lib/models/note.js
As we know the length of an UUID we can check if the base64 string 
of the provided UUID is long enough for a legacy base64 encoded
nodeId and stop processing it in legacy mode, if it's not the case.
This should make the ugly warning way less common.
/cc @dekonnection
=> Add check for noteId length

README.md, package.json, webpackBaseConfig.js
As we currently may need higher nofile limits than usual/default on
various systems this commit should probide a fix for that an allow to
build HackMD without highering these limits and increase security.
Inspiration was found in a [copy-webpack-plugin-issue][1] and found by
@thegcat. Thanks for that!
[1]:
https://github.com/webpack-contrib/copy-webpack-plugin/issues/59#issuecomment-228563990
=> Fix possible file limit errors

lib/letter-avatars.js, lib/models/user.js, lib/web/userRouter.js
To prevent further weakening of our CSP policies, moving the Avatars
into a non-inline version is the way to go.
This implementation probably needs some beautification. But already fixes
the bug.
Fixes #802
=> Move letter-avatars into own request

package.json
There was recently a possible security problem with base64url. Shouldn't
really hit us but it doesn't hurt.
Details: https://snyk.io/vuln/npm:base64url:20180511
=> Upgrade base64url package

lib/response.js
It's slightly annoying and confusing that I get a 403 error page for a note I can't access, even if I'm not logged in. A common solution in other apps seems to be redirecting the user to the login page. Since there doesn't seem to be a URL I can send the user to in this case, I redirect them to the home page and flash a message asking them to log in.
=> 403: Redirect user to login page if not logged in

public/vendor/md-toc.js
Right now the full title of an element is may not shown as the space of
the ToC is limited. With this path it'll be shower on hover and this way
provide more useful information.
Fixes #781
=> Add title attribute in table of contents

lib/web/imageRouter/filesystem.js, lib/web/imageRouter/imgur.js, lib/web/imageRouter/minio.js, lib/web/imageRouter/s3.js
Don't call the callback when it's undefined or not a function but log the error.
=> Fix callback validation

lib/config/default.js, lib/config/environment.js, lib/config/index.js, lib/migrations/20180326103000-use-text-in-tokens.js, lib/models/user.js, lib/response.js, lib/web/auth/index.js, lib/web/auth/oauth2/index.js, public/views/index/body.ejs, public/views/shared/signin-modal.ejs
The currently available OAuth methods are limited to a few providers. This PR implements a "generic" OAuth workflow which will fetch user profile info from a given JSON endpoint and extract a set of configurable fields. Example:
```json
"oauth2": {
"clientID": "test_hackmd_notasbad",
"clientSecret": "lc05GbmUT5crF33341CcpDbliG8KNW0HS4p9sS91Vx81",
"authorizationURL": "https://authprovider/oauth/authorize",
"tokenURL": "https://authprovider/oauth/token",
"userProfileURL": "https://authprovider/api/user",
"userProfileUsernameAttr": "username",
"userProfileDisplayNameAttr": "data.displayName",
"userProfileEmailAttr": "email"
}
```
I tried to guide myself by the existing OAuth provider definitions, please let me know if there are any better ways of doing what I'm trying to do.
=> Add "generic" OAuth2 support

app.js, lib/config/index.js
This commit should prevent the i18n module from adding missing
translations to the local files in setups that are not for development.
This way we keep the directory clean and idempotent.
Fixes #835
=> Fix i18n writing locale files in production

lib/migrations/20180525153000-user-add-delete-token.js, lib/models/author.js, lib/models/note.js, lib/models/revision.js, lib/models/user.js, lib/realtime.js, lib/response.js, lib/web/userRouter.js, locales/en.json, package.json, public/docs/privacy.md.example, public/js/cover.js, public/views/index/body.ejs
As GDPR kicked in today, we are pretty late on this.
It should provide some basic features that allow to run HackMD fine for GDPR. Not more, not less. Just enough for now.
When the next big re-factoring for user management comes, this should be redone.
=> GDPR compliant part 1

README.md
We wrongly state that the default image upload location is imgur. This
is no longer true, but got lost when updating docs. This commit should
fix it.
Fixes #842
=> Fix wrong docs about default image upload location

public/css/index.css, public/js/index.js, public/js/lib/editor/index.js, public/js/lib/editor/toolbar.html, public/js/lib/editor/utils.js
Simple toolbar with shortcuts to add Markdown elements as Heading, Bold, List, Image, etc.
It can be see running on the public instance of Hackmd on https://hackmd.okfn.de/
Signed-off-by: Edgar Zanella Alvarenga <e@vaz.io>
=> Add a toolbar to Codemirror editor

app.js, locales/zh.json
Since the original idea of using a symlink didn't work anyway, we should
remove the zh.json symlink from the repo.  It doesn't provide any
benefit but alters the repo on start of HackMD.
=> Remove unused zh.json from repo

README.md, lib/config/default.js, lib/config/index.js, lib/web/imageRouter/index.js
In https://github.com/hackmdio/hackmd/issues/834 is described how
starting HackMD crashes when using the wrong working dir.
This is caused by a relative path in our upload routine. This change
should fix it and prevent future crashes.
Fixes #834
=> Fix possible error if HackMD is started with wrong workdir

lib/web/imageRouter/filesystem.js
The image upload regex breaks with the new path for uploads.
This commit fixes it.
=> Fix breaking regex

lib/response.js
As it turns out, if the serverURL can't be generated correctly, HackMD
will use relative paths in image upload. This causes broken links in
PDF.
With this commit we force absolute links during PDF creation which
hopefully fixes the problem.
Fixes #820
=> Fix broken images in PDF caused by misconfigred server URL

lib/response.js
By uploading a malicous note currently it is possible to prevent this
note from being edited. This happens when using Windows line endings.
With this commit we remove all `\r` characters from the notes and this
way prevent this problem.
Fixes #822
=> Fix possible line-ending issues for init note

app.js, lib/config/default.js, lib/config/index.js, lib/web/statusRouter.js, public/views/includes/scripts.ejs
Since static path is providing with a high expiration data, we provide
configs via API. This shouldn't add any noticeable load while making it
uncached and this way working again.
Fixes #847
=> Move config out of statics path

README.md, lib/config/default.js, lib/config/environment.js, lib/letter-avatars.js, lib/models/user.js
Since Gravatar is an external image source and not perfect from a
privacy perspective, forbidding it allows to improve privacy.
This commit also simplifies and optimizes the avatar code.
Fixes #840
=> Allow to disable gravatar

public/docs/slide-example.md, public/js/slide.js, public/views/slide.ejs
It redirects the user to the print view of the document. I claim that
people should either be smart enough to use ctrl+P or ask someone who
knows how to print a webpage. I don't want to babysit our users.
Fixes #33
=> Add Print icon to slide view

public/js/lib/config/index.js
It wasn't possible to create unicode based URLs in freeurl mode, because
the noteid used for the websocket connection is double escaped. When we
decode it and let socketio-client reencode it, we get the real
shortid/noteid and can find the note in the database and open the
connection.
Fixes #729
=> Fix broken unicode urls

lib/web/statusRouter.js
As it turns out, expressjs doesn't detect the right mimetype and it
seems like I didn't bother to test this enough. So lets fix it for the
next release.
Fix #882
=> Fixing content types in status router

lib/config/index.js
Hi,
It's easy to fail to realize that images are uploaded to imgur by default (I just got bitten by this), and this can be an issue in some situations.
I wrote this trivial patch to default to a filesystem upload, in case others think the same.
Not sure if I should bump the version number though, let me know if it's the case!
I'll update the docs where needed if this PR gets the green light.
=> Upload images to the filesystem by default, rather than to imgur

README.md, app.js, lib/config/default.js, lib/config/environment.js
hi,
this patch adds two new config options to specify where the server listens (along with corresponding environment variables and documentation):
- `host`: specifies the host on which to listen, allowing restriction to a particular IP
- `path`: specifies the path to a unix domain socket on which to listen (takes precedence over `host`/`port`)
=> Support 'host' & 'path' config options

lib/migrations/20150702001020-update-to-0_3_1.js, lib/migrations/20160112220142-note-add-lastchange.js, lib/migrations/20160420180355-note-add-alias.js, lib/migrations/20160515114000-user-add-tokens.js, lib/migrations/20160607060246-support-revision.js, lib/migrations/20160703062241-support-authorship.js, lib/migrations/20161009040430-support-delete-note.js, lib/migrations/20161201050312-support-email-signin.js
I found some problems when upgrading from 1.1.1 to 1.2.0 and all of them were related to duplicated keys. In my case, these changes solved the issue.
Thanks to @SISheogorath since it is based on pull request #877
=> Add missing catch blocks for migration from 1.1.1 to 1.2.0

public/views/index/body.ejs
Replace the index page bottom social links of Twitter and Facebook to Riot chat.
To avoid making people confuse and let them ask in the place with better support.
=> Update to replace Twitter and Facebook to Riot

lib/letter-avatars.js
It seems like some providers return strange types for emails which cause
problems. We default to something that is definitely a string.
Fixes #903
=> Fix possible weird objects as email

lib/migrations/20150702001020-update-to-0_3_1.js, lib/migrations/20160112220142-note-add-lastchange.js, lib/migrations/20160420180355-note-add-alias.js, lib/migrations/20160515114000-user-add-tokens.js, lib/migrations/20160607060246-support-revision.js, lib/migrations/20160703062241-support-authorship.js, lib/migrations/20161009040430-support-delete-note.js, lib/migrations/20161201050312-support-email-signin.js
The current error handling seems to conflict with some sequelize
versions. So we add a second version of it in our excemptions.
I'm not happy about it, but when it helps to prevent further migration
breaking, it's worth it.
=> Extend migration error handling

lib/response.js
`markdown-pdf` seems to fail to provide the PDFs on tmpfs. This leads
crashing codimd which expects the file to be there. This patch should
add some proper error handling when expectation and reality don't fit
together.
=> Fix server crash on PDF creation

public/views/index/body.ejs
We broke the follow us before by removing Facebook and Twitter. Adding
POEditor should fix it and help to attract new translators.
=> Add POEditor to 'follow us' statement

lib/response.js
We recently introduced a new way to create notes using a post request
to the `/new` endpoint. This is not limited in size, other than pasting
a note in the editor. This patch should enforce this limit also on this
way.
=> Fix document length limit on post

public/views/index/body.ejs
Removing copyrigt sign since we are not copyrighting things.
Changing hackmd.io to codimd.org since HackMD is more and more dividing
from CodiMD and may brings up wrong expectations.
=> Some minor footer improvements

public/docs/features.md
Since the youtube video on our feature page seems to have vanished, this
patch replaces it with an video of the blender foundation.
=> Replace youtube example video on features page

docs/guides/auth/ldap-AD.md
Since our documentation on our LDAP configs is quite small, I add this
example for LDAP in an Active Directory environment.
=> Add documentation for an LDAP setup against Active Directory

app.js, package.json
`uws` was deprecated by its maintainer and starts to cause more and more
problems and issue reports. So it's time to replace it and use a
maintained project instead. Lucky us, `uws` and `ws` can be used in an
identical way, without problems. To provide better performance, we
install the optional packages as well.
=> Replace `uws` with `ws` package

package.json
Seems like we have to explicitly tell the new webpack version that we
want to use the development environment. This provides us with source
maps and similar.
This patch adds the commandline option in our scripts in package.json
=> Add development mode for webpack in package.json

README.md
Support includes v9.x, but no v10.x
Console message:
```
error CodiMD@1.2.1: The engine "node" is incompatible with this module. Expected version ">=6.x <10.x". Got "10.11.0"
```
https://github.com/nodejs/Release
Node.js LTS 10.x starts in October and i saw no PR to change compatible version
=> Update supported node.js version

public/js/index.js
The test was not on the right type, so the Visibility attribute was always empty.
This PR fix the test and gives a default value ("private") for Visibility of snippets.
=> Fix #986 : Visibility is now transmitted with gitlab V4 api

README.md, lib/config/default.js, lib/config/environment.js
Right now the feature exists but is almost not usable since the only way
to configure it is to know that it exists from reading the source code
and add it to config.json. This patch provides all needed changes so it
can be used by everyone including documentation.
=> Make oauth2 provider name accessible

package.json, public/views/codimd/head.ejs, public/views/html.hbs, public/views/index/head.ejs, public/views/pretty.ejs, public/views/slide.ejs, webpackBaseConfig.js
This patch replaces font-awesome with its fork called fork-awesome.
Besides the fact that the newer versions of font-awesome can't be
shipped with distros like debian due to license issues, fork-awesome
also provides more FOSS related icons and builds on top of version 4.7.x
of font-awesome, which we used until this patch.
Related: https://github.com/ForkAwesome/Fork-Awesome/issues/64
=> Replace font-awesome with fork-awesome

package.json, public/css/github-extract.css, public/js/extra.js, public/views/codimd/head.ejs, public/views/html.hbs, public/views/pretty.ejs, public/views/slide.ejs, webpack.common.js
Octicon no longer provides its CSS classes and this way is useless in
CodiMD. Replacing all used classes in the UI and remove it from build
system.
=> Remove dead package octicon

lib/csp.js, package.json
Seems like the old version of helmet had a problem with `data:`. This
patch upgrades to the latest version and adds the CSP rule to allow
Google Fonts and the offline version of it, to properly include the
fonts and no longer throw ugly error messages at us.
=> Add `data:` URL to CSP and upgrade helmet

public/js/index.js
Right now we support code highlighting for rust, but it doesn't appear
in autocomplete of codemirror, because codemirror is not aware of it.
This patch lets highlightjs simply tell codemirror, what it supports and
adds this to the autocomplete list.
=> Add autocomplete for highlight.js languages into codemirror

README.md, locales/en.json, public/docs/features.md, public/views/shared/help-modal.ejs
We no longer use Gitter for development talk and similar. So we might
want to remove it?
This patch removes Gitter from README, help page and features page. And
replaces it in the help modal with POEditor, our translation platform.
=> Remove Gitter from codebase

public/js/extra.js
Currently we have some emojis that are autocompleted but won't show up
in the resulting document.
This patch adds all emojis that are pushed to Codemirror and applies
them to the markdown rendering process, so they become usable.
Fixes #220
=> Fix not rendered autocomplete emojis

public/docs/slide-example.md
The printing instructions seem to not be really clear. Linking the
reveal.js offical docs should help.
=> slide example: Add link to slide printing instructions

public/js/extra.js
The old regex, adapted from the other plugins, was a bit too open for
matching. This leads to matching something like: `This is a sentence:
[And something with a: in it.]()` which doesn't become a link anymore.
Because the match is: ` [And something with a`.
This patch provides a fix for the regex to only match non-space string
within the `:`'s.
References:
- Introducing commit:
https://github.com/hackmdio/codimd/commit/2063eb8bdf9c0537e9fcfadd7f587658c72bd281
- Inspirational source of the original RegEx:
https://github.com/hackmdio/codimd/blob/2063eb8bdf9c0537e9fcfadd7f587658c72bd281/public/js/extra.js#L1095
=> Fix emoji regex

public/js/extra.js
The Regex introduced in the last commit, was already working quite
good. But still resulted in false positives for all URL that contained a
second `:`.
To fix this once and for all, we craft a simple, but long regex based on
all emoji names and use this to match them.
We could probably optimize it, but that should also be something the
regex engine itself can and should do.
Reference: 7e45533c75a3697c916e52e5f4ddff42a38bd3d5
=> Again: Replace emoji-plugin regex

app.js, lib/config/index.js, public/views/codimd/header.ejs
When gitlab is enabled with scope API, the menu Export/Import Snippets is not displayed.
This is because gitlab var stay indefined in public/views/codimd/header.ejs.
The fix here is to add a var `enableGitlabSnippets` and then use it in header.ejs.
=> Fix menu when gitlab is enabled

README.md, app.js, lib/config/environment.js, lib/config/index.js, lib/config/utils.js, lib/realtime.js, lib/web/statusRouter.js, locales/en.json, public/views/index/body.ejs
Currently we only provide the version from `package.json`. This means
that during updates of instances, e.g. the demo instance, which runs
latest master instead of a stable release, changes are not reflected to
the webclient.
This patch adds a fullversion string that contains the current commit
and this way makes that clients are notified about changes.
Also adds an automated detection for AGPL clear violations and asks the user for fixing it in production environments.
=> Add full version string (and no AGPL violation detection)

lib/config/default.js
We should use the official OS temp directory instead of an own one, to
not run into conflicts. Also various dependencies already use the OS
temp directory, which makes it pointless to use a different for our
internal purposes then. This commit provides the changes needed to use
the OS tmp directory by default.
=> Use OS based tmp dir

lib/config/utils.js
Right now we use a substr after reading the commit. That's definitely 
wrong and leads to wrong commit hashes since the first 5 chars are 
missing.
This patch removes the substr usage here and this way fixes the 
generated links.
=> Fix wrong reading from commit

docs/guides/migrate-etherpad.md
I recently migrated from Etherpad to CodiMD and migrated the pads
that were still on Etherpad. On Matrix [it was mentioned](https://matrix.to/#/!ybaSlrrMNLeuoQuUuR:matrix.org/$1541666805641585LnWVS:matrix.org) that a migration guide for Etherpad would be a useful contribution.
In this guide I share how a migration can be done. I am not completely sure if the script that is included is
completely error-free. Readers/reviewers should be aware that there may be bugs.
=> Add an etherpad migration guide

public/docs/features.md
Codemirror provides various modes via keymapping. These are already
available by a menu in the interface. But they aren't mentioned
anywhere.
This patch provides some documentation about the editor modes and their
implications. Since they are a feature, the documentation is done on the
features page.
=> Add documentation about editor modes in features page

app.js
ExpressJS still does allow serving index.html files. This change
disables that permanently.
=> Enforce disabled index for static assets

lib/response.js
Right now, you can't perform the `/download` action on a published note.
Currently, with a normal note, `/download` works:
```
https://hackmd.io/B58Juygfrj4rg8AgdA/download    // ✔️ 
```
But, with the published, `download` isnt an allowed action:
```
https://hackmd.io/s/dtG9j/download         // ⛔️ 
```
This PR makes it so `download` works on published notes:
```
https://hackmd.io/s/dtG9j/download         //  ✔️
```
I think `download` should be an allowed action on published notes - published notes are read-only and downloading is a read-only operation - and it allows for a API-ish endpoint for easily downloading published notes.
🍕 
Signed-off-by: Alex Garcia <alexsebastian.garcia@gmail.com>
=> Add download action to published notes

lib/web/auth/oauth2/index.js
In case anything goes wrong while fetching the profile, the login process would fail with a `502` because the InternalOAuthError does not exist within passport.
This fixes it, as demonstrated in #1056. It is not ideal, yet (the error itself is nowhere to be found), but at least it does not crash the server any more.
=> InternalOAuthError is not part of passport, but of passport-oauth2 #1056

app.js, lib/logger.js
During the upgrade of winston in 
c3584770f24205d84b9399abd9535cb27dc7b00c a the class extension for 
streaming was removed.
This caused silent crashes. Somehow winston simply called 
`process.exit(1)` whenever `logger.write()` was called. This is really 
bad and only easy to debug because of the testing right after upgrading.
However, reimplementing the stream interface as it was, didn't work, due 
to the fact that `logger.write()` is already implemented and causes the 
mentioned problem. So we extent the object with an `stream` object that 
implements `write()` for streams and pass that to morgan.
So this patch fixes unexpected exiting for streaming towards our logging 
module.
References:
https://www.digitalocean.com/community/tutorials/how-to-use-winston-to-log-node-js-applications …
=> Fix streaming for winston

bin/setup, package.json
Since we use `yarn` for our container setup and try to enforce
dependencies, we should also use yarn in the setup script.
=> Some minor improvements for setup script

README.md, lib/config/default.js, lib/config/environment.js, lib/response.js
Add a configuration setting to "hard"-disable creation of notes as set by the configuration value `CMD_FORBIDDEN_NOTE_IDS`. This defaults to `['robots.txt', 'favicon.ico']`, because these files are often accidentally created by bots and browsers.
As of now, it does not seem that a custom `robots.txt` file is needed. Looking from the other code in the source tree the general convention seems to be using `x-robots-tag` headers. So we can just return a `404 Not Found` error on `/robots.txt`.
However, we don't want to break an installation that already has these notes created (purposefully). So instead of blocking requests to `/robots.txt`, we will block any request to create it.
This PR fixes #1052.
=> Disallow creation of robots.txt in freeurl

public/views/index/body.ejs
Seems like ids in Firefox are case sensitive. So linking in the current 
way fails.
This patch fixes the links by using the exact matching version of the 
titles on the features page.
=> Fixing links on index page

README.md
Keeping people in the loop about new version of CodiMD is not easy. When
people don't keep an eye on GitHub it's easy to miss new versions.
To help people keeping their software up to date, this patch adds hints
to check out our community channel or simply the GitHub Atom feed
generated for based on the release page to get informed about new
versions.
=> Add hints about how to be informed about updates

public/js/extra.js, public/js/index.js, public/vendor/md-toc.js
Right now, the ToC has an undefined variable i that was an index in the 
original ToC code. Since the major rewrite in 
4fe062085324c50f2cfa062258559cf31858ef5f it's a recursive function 
without this index. The variable `i` was wrongly copied into its current 
place from the old code.
This patch replaces the variable `i` with the index of the header 
element. Fix the undefined variable problem.
Fixes #1042
=> Fix ToC breaking documents with empty h* elements

package.json, public/views/slide.ejs
There is a new reveal.js version out. As we try to keep up with
upstream, time to integreate it.
This patch updates reveal.js in for CDN-using instances as well as the
ones using the libraries.
Checked that speaker view in slide mode still works, so no CSP change
needed.
https://github.com/hakimel/reveal.js/releases/tag/3.7.0
https://github.com/hackmdio/codimd/blob/2d241b93002a3a23f81ffe8fab82f2c6c98feca4/lib/csp.js#L72-L74
Fixes #1009
=> Update reveal.js to version 3.7.0

lib/models/user.js, package.json
Since our previous scrypt library is unmaintained since 3 years, it's
time to look for an alternative.
A refactoring towards another password algorithm was worked on and this
is probably still the way to go. But for now the successor of our
previous library should already be enough.
https://www.npmjs.com/package/scrypt (old library)
https://github.com/ml1nk/node-scrypt (new library)
=> Switch scrypt library to a successor

.travis.yml, package.json
In my local environment I switched to Fedora 29. Fedora 29 comes with
NodeJS version 10.
As far as I can say, it works, so let's try to remove the restriction to
"<10.x"
**Edit:** We should also consider to provide 1.4.0 (yes, explicitly not 1.3.0) using Node version 10 in the container images.
=> After removing ws, node version 10 should work

config.json.example
We recently added the new logging option. As it turns out, the new
option was not added correctly, which points out that our current json
linting is **not working**. It throws an error but doesn't break.
This patch fixes the typo in the example. It does not fix the CI part.
=> Fix typo in config.json.example

package.json
We currently install `uuid` and `node-uuid`. `node-uuid` is deprecated
in favor of `uuid`. It seems like we already switched a while ago, but
somehow missed to remove the dependency.
This patch does exactly that. It removes the dependency from
`package.json` and this way removes the warning during install about
`node-uuid` being deprecated.
=> Remove node-uuid

package.json
When installing doctoc it throws some warnings about the markdown-to-ast
package that moved to an own namespace.
This patch updates to the version containing the new, namespaced,
package.
References:
https://github.com/thlorenz/doctoc/pull/151
=> Update doctoc to version 1.4.0

lib/csp.js
Disqus loads it's embed config.js from its root domain
(https://disqus.com). Our CSPs only allow subdomains (e.g.:
https://codimd.disqus.com). This causes the disqus embedding to fail.
This patch should fix this problem by adding https://disqus.com to the
CSP setting. From a security perspective there is no real change. Since
still the same parties are involved.
=> Fix disqus CSP

lib/csp.js
Looks like I was wrong in my previous commit to update revealjs.
The speaker notes broke again with the CSPs. So this patch updates the
hash and this way the speaker notes.
bcebf1e8d285184f8c905f00e0270621790e7b80
Signed-off-by: Sheogorath <sheogorath@shivering-isles.com>
=> Fix CSP for speaker notes

lib/web/imageRouter/filesystem.js
Due to the deprecation of the old `url`-API provided by NodeJS we
replaced `url.resolve` with `url.URL.resolve`, which doesn't exist.
This patch fixes the local filesystem upload of CodiMD by using the new
API correctly. Creating an URL object and using its href.
Some more background:
https://nodejs.org/api/url.html#url_url_href
https://nodejs.org/api/url.html#url_url_resolve_from_to
Fixes https://github.com/hackmdio/codimd/issues/1102
=> Fix usage of new URL API

lib/csp.js
Looks like GitHub changed their asset system and our CSP prevented them
from getting loaded.
This patch should fix the Gist embedding with enabled CSP by replacing
the old URL `https://assets-cdn.github.com` with the new
`https://github.githubassets.com`.
=> Fix broken Gist embedding

lib/letter-avatars.js, package.json, test/letter-avatars.js
This removes the blueimp-md5 hashing module, in favor of the one in the standard library. As requested by @SISheogorath, it also adds a test to see if everything still works (could be a beginning for  #611?). If requested, I'll remove the test again.
Fixes #1106.
=> Remove blueimp-md5 dependency

package.json
Seems like there was a security problem with the library.
This patch updates to version 1.0.0 which fixed the details.
Details: https://snyk.io/vuln/SNYK-JS-PASSPORTSAML-72411
Signed-off-by: Sheogorath <sheogorath@shivering-isles.com>
=> Update SAML to version 1.0.0

package.json, public/views/codimd/foot.ejs, public/views/codimd/head.ejs, public/views/html.hbs, public/views/index/foot.ejs, public/views/index/head.ejs, public/views/pretty.ejs
Seems like finally there is a new bootstrap version for old version 3.
This patch implements this new version with CodiMD and this way fixes
some possible security issues in the frontend code.
See:
https://snyk.io/vuln/SNYK-JS-BOOTSTRAP-72889
https://snyk.io/vuln/SNYK-JS-BOOTSTRAP-72890
Signed-off-by: Sheogorath <sheogorath@shivering-isles.com>
=> Update bootstrap from 3.3.7 to 3.4.0

bin/manage_users
Commit c3584770 upgrades Winston and with that version
`logger.transports.console` becomes undefined. This commit
updates the code to prevent the crash.
As far as I know, no issue was submitted for this bug.
=> Fix broken manage_users after Winston upgrade

package.json, test/csp.js
Since we lack of tests but got some great point to start, let's write
more tests.
This patch provides some basic tests for our CSP library. It's more an
integration than a unit test, but gets the job done.
=> Add tests for csp.js

package.json, test/letter-avatars.js
The tests are currently not linted. This causes a different coding style
than the rest of the sources.
This patch adds the `./test` directory to the eslint testing and fixes
linting for existing tests.
=> Add linting for tests

package.json
this commit has been blatantly stolen from @samselikoff in ember-cli-addon-docs. It prevents an issue introduced via a deep dependency that no longer supports node 6 (which we still would like to support).
see: https://github.com/ember-learn/ember-cli-addon-docs/commit/231275b5a4bed59bbac798ddaa1bde94319047cb
see: https://github.com/salesforce/tough-cookie/pull/141
The pull request should tell us, if this satisfies Travis.
=> Fixing deep dependency problem with node 6.x

public/docs/features.md, public/js/extra.js, public/js/index.js
The current speakerdeck implementation is broken. An alternative
implementation using oembed doesn't work due to CORS, which could be
solved by proxying the speakerdeck API, but we decided to not do this.
This patch provides the link to the speakerdeck presentation instead,
and this way doesn't break existing notes. This is right now the best
solution we could come up with.
=> Remove broken speakerdeck embedding

README.md
I tried to installed CodiMD on a new Debian 9 install. It was difficult to find out the dependency on the package `libssl-dev` introduced by this [commit](https://github.com/hackmdio/codimd/commit/cee2aa92f9244d1dcfc65c5553f5d7f0bbfb3871).
This PR proposes a mention of this dependency in README.md.
=> Mention dependency on libssl-dev in README.md

lib/response.js
If serverurl is empty and session was expired, redirect doesn’t properly.
302 Found
Location:
=> Fix empty serverURL did not redirect properly

lib/web/auth/google/index.js
Since Google+ is shutting down soon, we need to get the profile data
from another URL. Since the library already supports it, all we need to
do is adding a single line of code.
Fixes https://github.com/hackmdio/codimd/issues/1160
=> Add required change for Google+ API deprecation

lib/config/index.js
To provide a GitLab integration we need the GitLab integration to be
configured. Otherwise we shouldn't show the Snippet button.
This patch adds the requirement to the variable that decides if the
import from snippets button shows up or not.
=> Fix shown but broken GitLab snippets

public/js/extra.js
HTML export was broken due to missing alt-attribute for emojis.
This patch adds the old alt-element style and restores the exportability
this way.
Fixes #1164
=> Fix broken HTML export with emojis

lib/response.js
When creating a new note with the API, the note doesn't appear in the history. 
If the URL returned by the API is lost, or never accessed, then the note is lost, and the owner can't access it.
This pull request updates the history on note creation.
=> Update history on note creation

lib/web/imageRouter/minio.js
With the current state this behaviour is enabled by default and can be disabled by setting
```json
{
"minio": {
"hideDefaultPorts": false
}
}
```
or `CMD_MINIO_HIDE_DEFAULT_PORTS=false`.
Fix #1094
=> Hide default ports from minio image upload urls

lib/web/imageRouter/filesystem.js
Hi, I encountered codimd crash if url.js throws ERR_INVALID_URL.
```
2019-04-17T09:58:38.426Z error: 	uncaughtException: Invalid URL: /uploads/
TypeError [ERR_INVALID_URL]: Invalid URL: /uploads/
at onParseError (internal/url.js:219:17)
at parse (internal/url.js:228:3)
at new URL (internal/url.js:311:5)
at new URL (internal/url.js:309:14)
at Object.exports.uploadImage (/codimd/lib/web/imageRouter/filesystem.js:19:19)
at /codimd/lib/web/imageRouter/index.js:31:22
at IncomingForm.<anonymous> (/codimd/node_modules/formidable/lib/incoming_form.js:107:9)
at emitNone (events.js:106:13)
at IncomingForm.emit (events.js:208:7)
at IncomingForm._maybeEnd (/codimd/node_modules/formidable/lib/incoming_form.js:557:8)
at /codimd/node_modules/formidable/lib/incoming_form.js:238:12
at …
```
=> Fix avoiding crash if URL is invalid

lib/web/userRouter.js
I think a 401 status code should be more appropriate than 200 when the user is not recognized.
=> Adding an error code to the `{"status":"forbidden"}` response

lib/config/default.js, lib/config/environment.js, lib/config/hackmdEnvironment.js, lib/web/middleware/tooBusy.js
Make [toobusy-js](https://github.com/STRML/node-toobusy) maxLag parameter configurable with environment variables.
Default value is 70ms.
=> Make toobusy.maxLag configurable

webpack.common.js
Error:
```
[Script Loader] ReferenceError: Raphael is not defined
at Module.eval (eval at module.exports (addScript.js?f2b5:27), <anonymous>:1:113133)
at e (eval at module.exports (addScript.js?f2b5:27), <anonymous>:1:110)
at eval (eval at module.exports (addScript.js?f2b5:27), <anonymous>:1:902)
at eval (eval at module.exports (addScript.js?f2b5:27), <anonymous>:1:913)
at eval (<anonymous>)
at module.exports (addScript.js?f2b5:20)
at eval (main.js?b289:1)
at Object../node_modules/script-loader/index.js!./node_modules/@hackmd/js-sequence-diagrams/build/main.js (index-pack.js:12798)
at __webpack_require__ (index-pack.js:20)
at Object.8 (index-pack.js:13991)
```
=> Fix js-sequence-diagrams bundling

public/js/extra.js
Fix potential JSONP callback overwritten in Slideshare/Vimeo/Gist external embed syntax.
=> fix(security): potential JSONP callback overwritten

app.json, bin/heroku, package.json, yarn.lock
In order to fix heroku on-click deployment, I 
- edited package.json to not use unsupported nodeJS ( <12.0.0)
- removed dialect from .sequelizerc file
- add once-removed `postinstall` section in package.json
- removed `DB_TYPE` not used anymore
- removed `npm_run_build` which is run twice
close #1206 
close #1200
=> fix heroku one click deployment

public/js/render.js
Patch for #1263
Because sandbox is whitelist attribute, attacker will be able to create iframe that has more permission than default.
I'm not sure `sandbox` is commonly used, but at least this should be removed because of this leads XSS in some browsers.
=> Remove sandbox attribute

app.json, bin/heroku
Remove unnecessary `BUILD_ASSETS` environment variable. We can check whether it runs on heroku by the `DYNO` env
=> Remove BUILD_ASSETS environment variable

app.js, lib/config/default.js, lib/config/environment.js, lib/config/index.js, lib/realtimeClientConnection.js, public/views/codimd/body.ejs, test/realtime/socket-events.test.js
resolve #1144
allowAnonymousViews : set to `false` to delete `freely`, `editable` and `locked` permission when allowAnonymous is true (default is `true`)
e.g.
`allowAnonymous=false`
`allowAnonymous=false` and `allowAnonymousViews=false`
`allowAnonymous=false` and `allowAnonymousEdits=true`
| allowAnonymous | allowAnonymousEdits | allowAnonymousViews | `New guest note` button | `freely` permission | `editable/locked` permission | 
| -------- | -------- | -------- | -------- | -------- | -------- |
| true | - | - | active | active | active |
| false | - | false | inactive | inactive | inactive |
| false | false | true | inactive | inactive | active |
| false | true | true | inactive | active | active |
=> Add allowAnonymousViews option

deployments/Dockerfile
fixed wrong file permission setting in 1.4.0-rc.1 caused user can't upload image
=> fix: image upload caused permission denied error in docker

config.json.example, lib/config/default.js, lib/config/environment.js, lib/web/statusRouter.js, public/js/extra.js, public/js/lib/common/constant.ejs
resolves #1305 
This makes the references consistent/compatible with GitHub,
GitLab, Pandoc and many other tools.
This behavior can be enabled in config.json with:
```
"linkifyHeaderStyle": "gfm"
```
=> Allow to generate lower case header references through the config

lib/web/auth/gitlab/index.js, package.json, yarn.lock
fixes #1295 
This adds support for GitLab OAuth where the GitLab server is behind a corporate proxy.
It checks for the `https_proxy` environment variable, and if it exists, will use that value as the HTTPS proxy.
=> Add https_proxy support to gitlab oauth

lib/config/default.js, lib/config/environment.js, lib/web/statusRouter.js, public/js/extra.js, public/js/lib/common/constant.ejs, public/js/slide.js
resolves #1212 
This PR introduce a new configuration entry let you follow CommonMark spec break behavior:
|Set `config.defaultUseHardbreak` to `true` <br> (Current CodiMD implementation) | Set `config.defaultUseHardbreak` to `false` <br> (CommonMark)|
|--|--|
|![Screen Shot 2019-10-20 at 2 22 00 PM](https://user-images.githubusercontent.com/4230968/67155637-9f27f600-f345-11e9-8ed7-74c17f024de1.png)|![Screen Shot 2019-10-20 at 2 22 39 PM](https://user-images.githubusercontent.com/4230968/67155641-bcf55b00-f345-11e9-87d6-f34f8788bc58.png)|
Notice that we keep the default `defaultUseHardbreak` value to `true` for preserving the current behavior.
- https://github.com/jdhoek/codimd/commit/c12a8d2fddf496966f64ccabc688f3a09320ea90 in https://github.com/hackmdio/codimd/issues/1212#issuecomment-50 …
=> Configurable default break style

deployments/Dockerfile, deployments/docker-compose.yml, deployments/docker-entrypoint.sh
fixed #1347, 
fixed #1351 
1. upgrade node.js version from 8.16.0 to 8.16.2
2. upgrade pcheck to support connection string from environment
3. upgrade pcheck to fix connection string contains underscore might not resolve correctly
=> fix pcheck not parsed url correctly

package.json, yarn.lock
fixed #1356 
Need to manually install mysql2 package when sequelize upgraded
=> fix: mysql2 not install

bin/manage_users
fixes #1369 
The manage_users script currently does not work in the official docker image, since it compares to undefined. However, the returned variable is null, resulting in crashing of the script. (see #1369)
Additionally, I changed a return code in the `createUser()` function. This allows other scripts to distinguish between the failure reasons.
=> Fix #1369 - make manage_users work again

lib/web/imageRouter/s3.js
This works around permission problems with DigitalOcean spaces (where files are always *private* by default).
This should not pose a difference with AWS and other providers as CodiMD only works with public S3 assets either way.
=> Explicitely set uploaded image ACLs for S3 to "public-read"

package.json, yarn.lock
Fixed #1354 
Cannot upload image to minio caused by package upgrade.
Temporary downgrade the version of minio to 6.0.
=> fix: minio cannot upload caused by package upgrade

app.js, app.json, lib/config/environment.js, lib/config/hackmdEnvironment.js, lib/config/index.js, lib/web/auth/bitbucket/index.js, lib/web/auth/index.js, package.json, public/views/index/body.ejs, public/views/shared/signin-modal.ejs, scalingo.json, yarn.lock
Some companies use atlassian cloud and it would be useful if the members can use CodiMD with bitbucket account.
----
We can deploy the CodiMD with Bitbucket suuport with the Heroku deploy link below:
https://heroku.com/deploy?template=https://github.com/YusukeIwaki/codimd/tree/feature/bitbucket_login
=> Add bitbucket Support

deployments/docker-compose.yml
PostgreSQL docker image has been raised from 11.5 to 11.6.
Also, the size is dramatically reduced by changing the base image to alpine.
[Image Layer Details - postgres:11.5 - sha256:e49ebd64ed6c0035aa5ee8626ff4d697800305f518da3c364ce9e9c306892c8b - Docker Hub](https://hub.docker.com/layers/postgres/library/postgres/11.5/images/sha256-e49ebd64ed6c0035aa5ee8626ff4d697800305f518da3c364ce9e9c306892c8b)
[Image Layer Details - postgres:11.6-alpine - sha256:f239499a66c151b93b79e8df0b3ca4b57704f4f9e66ff7e70ef60f5a4bb54753 - Docker Hub](https://hub.docker.com/layers/postgres/library/postgres/11.6-alpine/images/sha256-f239499a66c151b93b79e8df0b3ca4b57704f4f9e66ff7e70ef60f5a4bb54753)
If it is a minor update of 11.x system, it has been confirmed that it works normally because it is compatible. …
=> postgresql docker image upgrade 11.5 to 11.6-alpine

app.js, lib/config/default.js, lib/config/environment.js, lib/web/middleware/checkVersion.js
This PR implements a version checking functionality.
It would send the version number (e.g. `1.4.1`) to our version checking service (`evangelion.codimd.dev`) and log the result. Now it only does `console.warn` to let service admin know it's an outdated instance. For the future, we can add a more detailed UI for displaying such information.
=> Version check middleware & logging

public/js/extra.js
This PR fixes #1374 
- viz.js return Promise since version 2.0.0 and we didn't catch the error properly
- on catching error, we should recreate Viz instance to clean up the error, see more: https://github.com/mdaines/viz.js/wiki/Caveats
=> fix: catch viz.js render async error and recreate Viz instance

lib/csp.js, package-lock.json, package.json, public/docs/features.md, public/views/slide.ejs, test/csp.js, webpack.common.js
- upgrade reveal.js from 3.7.0 to 3.9.2
- remove head.js dependency after reveal.js 3.8.0
- update CSP nonce for speaker notes feature
- fix mermaid docs link in features.md
=> Feature/upgrade reveal.js 3.9.2

package-lock.json, package.json
- upgrade markdown-it from 9.0.1 to 10.0.0
- Fix quadratic parse time for some combinations of pairs, #583. Algorithm is now similar to one in reference implementation.
- support CommonMark spec 0.29
for example: ex***amp***le
https://github.com/markdown-it/markdown-it/commit/e519e6ac198221ace43685360647a3fce666df81
https://github.com/commonmark/commonmark-spec/commit/83ed53e12aa2e011b04474825bfb22a40682e4a0
=> feat: upgrade markdown-it to 10.0.0 for supporting em in strong tag

public/js/extra.js, public/js/index.js
The validate URL function `isValidURL` was borrowed from: https://stackoverflow.com/questions/5717093/check-if-a-javascript-string-is-a-url/43467144
for example: `https://doc-12-34-ssa-view.111/asdfasdfasdfasdfqweqweqwe`
adding more characters to the URL will cause catastrophic backtracking and leads to UI freezing.
=> fix: use validator.isURL to avoid regex catastrophic backtracking

public/js/extra.js
This PR fixed geo-map not parsed west longitude and south latitude corrlectly (caused by negative number of longitude and latitude)
=> Fix west longitude and south latitude not parsed correctly in geo map

lib/config/default.js
This is breaking change !!!
This PR change HSTS IncludeSubdomain setting to false.
In default setting, its will force subdomain use HSTS, but it's breaking the site that hosted in subdomain and didn't has SSL certificate.
=> Disable HSTS IncludeSubdomain, to prevent unexpected behavior

public/docs/release-notes.md
Fixes the problem where the link opens the same release notes page.
Signed-off-by: 林博仁(Buo-ren, Lin) <Buo.Ren.Lin@gmail.com>
=> Fix Wikipedia link in 2.0.0 release notes

public/js/extra.js, public/js/lib/syncscroll.js
You can use inline markdown in the spoiler summary syntax now:
```markdown
:::spoiler **click** me and [show](https://github.com/hackmdio/codimd) me the code
Hide me
:::
```
=> Allow inline markdown in spoiler summary syntax

public/css/extra.css, public/css/index.css
Partially fixes #1441. Increases contrast of some buttons. The color of line numbers wasn't changed in this PR, because it seems that it would require editing every theme separately.
=> Improve visibility of some UI elements

lib/note/index.js
Current check prevents creation of notes when allowAnonymous is disabled and user is logged in
=> Fix check for creating free url notes

lib/auth/oauth2/strategy.js, lib/config/default.js, lib/config/environment.js, lib/models/user.js
Enable OAuth users to have avatars from a field in `userProfileURL` or Gravatar.
=> Support avatar for OAuth users

lib/web/middleware/checkVersion.js
This PR' is to improve version checker behavior.
1. setup timeout to 1000ms: if server's network is unstable, may cause response too slow.
2. change logger type from warn --> info, error --> warn
=> Improve version checker behavior

.travis.yml, bin/manage_users, lib/auth/email/index.js, lib/models/user.js, package-lock.json, package.json
This PR replaced the unmaintained library `node-scrypt` with a replacement `script-kdf`.
There is a native API for scrypt support from Node.js 10+, and **Node.js 8 has reached it's EOL on Dec 2019.** I think it's safe to say we can now switch to use the native API. The node version required in `packages.json` has been changed to `>= 10, < 13`, but need more work to check if it is fully functioned in Node 12.
As I changed the dependencies, following changes has been made:
- The setter for `User.password` are now removed. As `scrypt-kdf` can only generate hashes asynchronized.
- Added a new async method `User.hashPassword`. We need to manually call this method when setting password.
- `User.prototype.verifyPassword` has been made async.
Besides, this means we should now be able to run …
=> Replace scrypt with scrypt-kdf

public/js/extra.js, public/js/lib/markdown/utils.js, public/js/lib/syncscroll.js
Now we support supply additional params in fence code language like:
~~~md
```fretboard {title="horizontal, 5 frets" type="h6 noNut"}
```
~~~
In post render functions, we can now use:
```diff
fretboard.each((key, value) => {
+	const params = deserializeParamAttributeFromElement(value)
+   assert.true(params.title === "horizontal, 5 frets")
```
FYI @birdca
=> Support brace wrapped param in fence lang

lib/models/user.js
At the moment, the URL is being composed and modified with the use of
string composition.
This causes issues, if the URL returned by GitHub slightly differs from
the time developer initially had a look into it.
In our case, the URL from GitHub has two query parameters in it, whilst
the codebase only expected one.
This change will take all of these parameters and only set the one we
care about, whilst leaving others intact and carry on with the full URL.
Fixes #1489
- Run locally with GitHub OAuth enabled
- Login with GitHub
- See your avatar displayed properly
- *optionally* Follow the same steps on the `develop` branch to see difference
=> Fix GitHub's avatar URL

lib/auth/oauth2/index.js, lib/config/default.js, lib/config/environment.js
state parameter is recommended with oauth2 authentification to mitigate CSRF attacks (see [auth0 doc](https://auth0.com/docs/protocols/oauth2/oauth-state)).
[hydra](https://www.ory.sh/hydra) will throw the following error message if state is missing:
```
description="The state is missing or has less than 8 characters and is therefore considered too weak" error=invalid_state hint="Request
parameter \"state\" must be at least be 8 characters long to ensure sufficient entropy."
```
closes #1511
=> fix: add state parameter for oauth2

lib/realtime/realtime.js, lib/status/index.js
Fixed #1516
The getStatus function will return logger object when app can't connect to database. This behavior caused /status throw "TypeError: Converting circular structure to JSON".
This PR fixed the getStatus function, reject promise when error occurs. And return status code 500 to indicate that server status is not fine.
=> Fix getStatus caused "TypeError: Converting circular structure to JSON"

deployments/Dockerfile, deployments/build.sh
1. upgrade nodejs version to 10.20.1
2. reduce docker images size from 1.8G to 800MB
3. separate fonts, introducing new image tag postfix `-cjk`. If you need export markdown to pdf with CJK fonts, please use the image that with psotfix `-cjk`
=> Change to use nodejs 10.20.1

deployments/docker-compose.yml
This PR change the docker image version to 2.1.0 in docker-compose.yml file.
=> chore: change image version to 2.1.0 in docker-compose example

public/js/index.js, public/js/lib/editor/ui-elements.js
Update to make editor have extra scroll padding in the bottom that can scroll over editor lines (or say scroll past end) and leave only one line on top of the editor.
This solves #617 #1207
=> Make editor can scroll over lines

lib/imageRouter/filesystem.js, lib/imageRouter/index.js
This PR fixes users using filesystem as image storage and not setup proper permission may caused application crash.
1. always uploads file to os temporary path (formidable library default behavior)
2. In filesystem image upload module, move temp file into upload folder and if has any problem, return error properly.
=> fix: improve image upload to filesystem may caused app crash

lib/models/note.js
> Recreating on a dedicated branch. Deprecates #1501
This patch introduces metadata tags in array format.
Metadata tags can be done by either using strings (like before):
```
---
tags: tag1, tag2, tag3
---
```
And, with this patch, also using arrays, in any YAML supported format:
```
---
tags:
- tag1
- tag2
- tag3
---
```
```
---
tags: [tag1, tag2, tag3]
---
```
This will make it more compatible with other software using structured types in the metadata section (I use CodiMD with other markdown software).
=> Use array for tags when available (close #1496)

package-lock.json, package.json, public/docs/features.md, public/js/extra.js, public/js/index.js, public/js/lib/renderer/csvpreview.js, public/js/lib/syncscroll.js
resolves #1436 
Example syntax:
~~~md
```csvpreview {header=true}
firstName,lastName,email,phoneNumber
John,Doe,john@doe.com,0123456789
Jane,Doe,jane@doe.com,9876543210
James,Bond,james.bond@mi6.co.uk,0612345678
```
~~~
- ~~codemirror overlay language mode~~ No existing csv language mode now
=> Implement csvpreview renderer

lib/note/index.js, public/docs/yaml-metadata.md, public/views/pretty.ejs
This is referencing the issue 'Support YAML metadata image tag #1545'
=> feature: pass-through yaml metadata image to html meta tag

.sequelizerc.example, config.js
Until now, the Sequelize CLI received options differently from the actual Sequelize instance created in `lib/models/index.js`. Aside from just being irritating, it prevents any database options from `config.json` from being used by the Sequelize CLI without duplicating them, as @Yukaii points out in #1396.
This PR has the Sequelize CLI use a `config.js` which uses `lib/config` to load the configuration just as the application does.
Fixes #1396
Signed-off-by: Maximilian Haye <mhajoha@gmail.com>
=> Allow Sequelize CLI to use options set in config.json

lib/note/index.js, lib/routes.js, package-lock.json, public/js/extra.js
1. CodiMD note content update API 
- PUT /api/notes/${noteId}
- body: (JSON) content: string
2. CodiMD note delete API 
- DELETE /api/notes/${noteId}
- Check owenerId
=> Update and delete note api

package-lock.json, package.json, public/js/extra.js
fixes #1568 
Now you can specify [render options](https://github.com/mdaines/viz.js/wiki/API#render-options) as key="value" within braces:
~~~md
```graphviz {engine="circo"}
digraph hierarchy {
nodesep=1.0 // increases the separation between nodes
node [color=Red,fontname=Courier,shape=box] //All nodes will this shape and colour
edge [color=Blue, style=dashed] //All the lines look like this
Headteacher->{Deputy1 Deputy2 BusinessManager}
Deputy1->{Teacher1 Teacher2}
BusinessManager->ITManager
{rank=same;ITManager Teacher1 Teacher2}  // Put them on the same level
}
```
~~~
Syntax reference: pandoc's `fenced_code_attributes`
=> Allow specifying option for graphviz

package-lock.json, package.json, public/js/lib/editor/spellcheck.js, webpack.common.js
This adds an "English (United Kingdom)" option to the list of spell checkers, using [`dictionary-en-gb`](https://www.npmjs.com/package/dictionary-en-gb).
=> Spellcheck: add en_GB dictionary

package.json
VSCode uses `jsonc` (JSON with comments) to parse the configuration files. Unfortunately this doesn't work well with `jq` which follows the JSON standard and errors out on comments.
=> Don't run jsonlint on .vscode jsonc files

public/js/extra.js
Fix #1630 
Avoid using element.html for putting back parsed string of mermaid where can trigger stored XSS attacks.
=> fix: avoid eval string when putting back parsed string of mermaid

public/js/extra.js
The JSONP callback data from vimeo is prepend with `/**/` which can't be parsed by jQuery.
=> fix: vimeo won't show up due to the jsonp callback data unable be parsed with jQuery

package-lock.json, package.json, public/js/extra.js
Also upgrade pdfobject to version 2.2.4
This might be a bug in Safari on Big Sur, make a workaround anyways.
=> fix: avoid insert embed tag on the main thread which cause Safari on Big Sur freezing

public/js/reveal-markdown.js, public/js/slide.js
Fixes #1648 
Since meta-marked uses js-yaml and parse meta with `yaml.safeLoad`, there is no way the yaml can get js function or regex out. We only need to remove library load external resources.
=> Fix slide mode stored XSS

app.json, package.json
Fix #1657 
- https://github.com/brianc/node-postgres/blob/4bc55834b93f945e3b60378db121e739e0950f92/CHANGELOG.md#pg810
- brianc/node-postgres#2281
- sequelize/sequelize#956
- https://devcenter.heroku.com/articles/heroku-postgresql#connecting-in-node-js
=> Enforce PG ssl require mode on heroku

lib/note/index.js
Hello,
This PR introduces the ability to use the newly provided update API anonymously, when the system is configured to work in anonymous mode (i.e. `allowAnonymousEdits` is true).
Also logging in case of error was extended with the stack trace to match similar code in the project.
The patch was successfully tested and is currently used in a pilot deployment, where CodiMD is being integrated with an external storage and controlled via API, therefore user authentication/authorization is delegated to the external storage. I can provide further information and hopefully more PRs that have helped in our integration.
=> Support anonymous updates via API if allowAnonymousEdits is true

lib/auth/utils.js, lib/response.js
When:
1) you are not logged in
2) and you try to view a private note
Then:
1) you are redirected to the home page and asked to log in
2) once you log in you are not redirected to the note
This PR fixes this situation and redirects user to a note on a successful login.
=> Better redirection after a successful login

README.md
Proposing to add matrix bridge to the list of available chats.
See also: https://element.io/blog/gitter-goes-native/
https://matrix.org/blog/2020/12/07/gitter-now-speaks-matrix
=> Add matrix badge and links to README

lib/config/default.js, lib/config/environment.js, lib/status/index.js, public/css/extra.css, public/docs/features.md, public/docs/yaml-metadata.md, public/js/extra.js, public/js/lib/common/constant.ejs, public/vendor/md-toc.js
This commit allows one to set the depth of the table of contents freely by means of YAML metadata or an option directly within the `[toc]` tag (e.g. `[toc maxLevel=4]`. The default level can also be set by means of the environment variable `CMD_DEFAULT_TOC_DEPTH`, this variable defaults to 3. The toc depth of the automatically generated toc can only be set by setting the level in the YAML or below.
The precedence of the toc depth is as follows (highest to lowest): `[toc maxLevel=4]` > YAML metadata > `CMD_DEFAULT_TOC_DEPTH` > 3 (default value)
+ [x] It might be nice to set a default depth with an environment variable, though I'm unsure how to access them from the frontend (as I found no example)
=> Set TOC depth freely for every note by using YAML metadata or an option within `[toc]`

app.js, lib/config/default.js, lib/config/environment.js, public/views/index/body.ejs, public/views/shared/signin-modal.ejs
Fix #1582 
Follow https://developers.google.com/identity/branding-guidelines (bootstrap-social is outdated)
and https://support.google.com/cloud/answer/9110914#all-apps-zippy
=> Follow Google guidelines to use Google OAuth

lib/auth/utils.js
As our cli tool is not passing referer header on requesting server, this will lead to fail login by PR #1609
=> Handle when request url has no valid referer

public/js/extra.js
Fix https://github.com/hackmdio/codimd/issues/1689
cc @lbherrera
=> Strip HTML tags for gist id to avoid stored XSS on showing error [Security Issue]

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .devcontainer/docker-compose.yml, package.json
This PR add dev container support.
refs:
- https://docs.github.com/en/codespaces/setting-up-your-codespace/configuring-codespaces-for-your-project
- https://code.visualstudio.com/docs/remote/containers
=> Add dev container for GitHub Codespaces and VSCode remote container

public/js/index.js
The function should match only the beginnings of lines.
For example, see this testcase:
```
:::spoiler
here is a :::
:::
:::
```
The last line should be completed, and the third should not.
Without this patch, the third line is completed and the last is not.
FYI, this patch is not perfect, either.
If the third line is ":::bogus", the parser won't treat it as the closer. But matchInContainer will.
So the right regexp would be /(^|\n):::\s*(success|info|warning|danger|spoiler)($|\s)/ but who cares
=> Fix matchInContainer false positives

public/views/codimd.ejs, public/views/codimd/body.ejs, public/views/codimd/foot.ejs, public/views/codimd/head.ejs, public/views/error.ejs, public/views/index.ejs, public/views/index/body.ejs, public/views/index/foot.ejs, public/views/index/head.ejs, public/views/pretty.ejs, public/views/slide.ejs
=> Convert "include" directives to functions

public/docs/features.md
I was wondering for a while why ABC music notation is in placed under "UML diagrams" section.
I created a dedicated Music section and put ABC and fretboard onto this section
=> Documentation - add Music section and move abc abd fretboard to this section

public/js/lib/markdown/utils.js
The change fixes an error while rendering diagrams using code fence parameters.
This closes #1738
=> Fix: Code Fence parameter parsing

lib/imageRouter/index.js, package-lock.json, package.json
I discovered server will crash when user trying to upload an image with filename too long.
After study the code I found it's caused by formidable, the old version not handle IO error properly cause this problem.
=> FIX: server crash when filename too long

.buildpacks, Aptfile
Fix the Scalingo deployment by using the Scalingo official recommandation for VIPS (https://doc.scalingo.com/languages/ruby/rails/start#use-vips-to-process-image).
=> fix(buildpacks): replace custom buildpack with APT buildpack

lib/note/noteActions.js
According to pandoc's [manual](https://pandoc.org/MANUAL.html#a-note-on-security)
some file format can include or embed files on the file system.
Check param `exportType` is valid & running pandoc with `--sandbox` to fix this.
=> FIX: pandoc security issue

lib/note/index.js
fixes: https://github.com/hackmdio/codimd/pull/1570
In the current version, if I call `PUT /api/notes/:noteId`, my note will be updated properly, but in history page, I will get 2 notes with the same name, one linked to `/uuid` (which can not be opened, 404) and the other linked to `/encoded_id` (this is what I want)
I did some digging, and noticed that both `note.id` and `noteId` here in `updateNote` are uuid, not encoded note id, we have to call `Note.encodeNoteId` to make it work
=> fix: use encoded note id to update history

app.json, config.json.example, lib/auth/github/index.js, lib/config/default.js, lib/config/environment.js, scalingo.json
Currently CodiMD does not support limiting access of GitHub OAuth users based on their organization membership. This is a very useful functionality for teams that want to limit write access to their notes.
I've implemented a crude solution to this problem, which most probably requires some adjusments to make it better. I'm not sure if this implementation is kosher, but it definitely works on my deployment.
Open to suggestions on how I can improve it.
=> feat: add organizations whitelist to GitHub OAuth

public/views/shared/disqus.ejs
Modify replacement rule for disqus short-name.
=> 🐛 [fix] modify replacement rule for disqus short-name

public/js/extra.js, public/js/utils.js
Hi team,
Consider the following example, which can trigger an alert popup when inline PDFs are unsupported (like on mobile devices):
```md
<span class="pdf raw" data-pdfurl="'><iframe srcdoc='ww<script src=&quot;https://www.google.com/complete/search?client=chrome&q=123&jsonp=alert(document.domain)//&quot;></script>'></iframe><p data-x='"></span>
```
The issue arises because [PDFObject](https://github.com/pipwerks/PDFObject) uses `innerHTML` to insert concatenated fallbackHTML, which could lead to XSS vulnerabilities. For more information, refer to https://github.com/pipwerks/PDFObject/issues/296
This can be seen in the code at the following locations:
https://github.com/pipwerks/PDFObject/blob/2c0bbd90d4de64598ff6df9e1af32de2d58a6eb9/pdfobject.js#L275 …
=> fix: sanitize pdf url to prevent XSS on inline PDFs

.github/tests/README.md, .github/tests/pull-request.json, .github/workflows/check-release.yml
Check if both `public/docs/release-note.md` and `package.json` are updated.
And yes, I didn't bump the version 2.5.2. 😓 That's the reason for this PR.
=> feat: add check-release workflow

deployments/docker-compose.yml
=> chore: update docker-compose default image version to 2.5.3

lib/migrations/20240114120250-revision-add-index.js
The SQLs to select records from the revision table is a sequential scan.
These SQLs use note id as a search key, but there is no index on the note id column.
I want to change to index scan to improve system performance 🚀 
The records in the revision table will become huge during operation, so sequential scans should be avoided.
This is especially because the following fetch processing is called frequently.
https://github.com/hackmdio/codimd/blob/d157fde6667185ab09125fa18317152eeef15fb4/app.js#L277
For your reference, the organization I belong to has already changed it. (https://github.com/kufu/hackmd/pull/19)
=> Add index at revision table for improving system performance  🚀 

.github/workflows/build.yml, .github/workflows/check-release.yml
Upgrade GitHub Actions to use `checkout@v4`, `cache@v4`, and `setup-node@v4` for improved performance and features.
=> Update GitHub Actions to use latest versions

lib/config/default.js, lib/config/environment.js, lib/imageRouter/s3.js
close #1872 
This change allows you to replace the S3 endpoint with a different domain, for example when distributing images using a CDN.
- Added `s3.baseURL` option.
- If `s3.baseURL` is set, the image URL will be changed to `${s3.baseURL}/${params.key}`.
=> Add baseURL configuration option to S3 modules

lib/imageRouter/s3.js
close: #1892
Fix the erroneous change in #1762.
=> Fix: Lost schema of S3 URL. 

public/js/extra.js, public/js/utils.js
Companion test script
A bun proxy server that serve xss content `https://william957-web.github.io/meow_xss.html`
```javascript
// pdf-proxy.js
const server = Bun.serve({
port: 5678,
async fetch(req) {
// Only handle requests to our proxy endpoint
const url = new URL(req.url);
if (url.pathname !== "/proxy-as-pdf.pdf") {
return new Response("Not Found", { status: 404 });
}
try {
// Fetch the original HTML content
const response = await fetch("https://william957-web.github.io/meow_xss.html");
const originalContent = await response.text();
// Return the HTML content with PDF content type
return new Response(originalContent, {
headers: {
"Content-Type": "application/pdf",
"Content-Disposition": "inline; filename=document.pdf"
}
});
} catch (error) {
console.error("Error fetching the content:", …
```
=> feat: add PDF URL validation and content type check

package-lock.json, package.json
Bumping Codemirror to version 5.65.8 addressed an issue on Firefox: The editor would break if the user tried to input after right-clicking on it.
=> chore/bump codemirror version to 5.65.8

lib/auth/email/index.js
fix #1744
By query email in lower case makes login be case insensitive now
tested on: Postgres12 & sqlite3
=> fix: login email should be case insensitive

.devcontainer/Dockerfile, .devcontainer/docker-compose.yml
Based on [what people say](https://github.com/microsoft/generative-ai-for-beginners/issues/187#issuecomment-1822014162), `14-buster` can't run on MBP ARM - but `14-bullseye` can. I was able to get it working.
Note that I saw some PhantomJS related errors in the terminal output, but that didn't prevent me from being able to contribute. But it likely means this PR isn't complete. :) Hope you could take it over and ensure it's good and everything.
=> VSCode: update image to allow development on MBP ARM chips

public/js/extra.js, public/views/codimd/foot.ejs, public/views/pretty.ejs, public/views/slide.ejs, webpack.common.js
- Added mermaid.min.js to the build output in webpack.common.js.
- Updated mermaid initialization in extra.js to use the new API.
- Included mermaid.min.js script in foot.ejs, pretty.ejs, and slide.ejs for rendering diagrams.
=> chore: integrate mermaid.js into the build process and update initialization in extra.js
