- lib/response.js
https://github.com/hackmdio/hackmd/commit/b6c758f2fc2cb502ed194f2700e033564f2521f4
> bugfix: useCDN option must be passed to ejs_renderer

- public/js/index.js
Esc key should work in the vim mode
> Fix Esc key in Vim mode

- public/css/cover.css
- public/js/cover.js
- public/views/index.ejs
Last one I swear lolol
Just adding the avatar to the history page over the "Welcome..."
Not sure if you were not showing it for a reason...just adds a little personalized touch to the screen.
> Add avatar to History page.

- README.md
One place I saw that needed updated.
> Add GitLab to Third-Party integration section.

- app.js
As per [this issue](https://github.com/expressjs/session/issues/365)
> Remove expiry from cookies

- public/js/index.js
Updated the wording of the placeholder text, mentioned in #180.
> Change wording of placeholder text

- public/js/extra.js
- public/js/index.js
- public/js/public.js
> Fix minor bugs (cont.)

- package.json
- public/js/public.js
- public/views/foot.ejs
- public/views/index.ejs
- public/views/pretty.ejs
- public/views/slide.ejs
- webpack.production.js
- webpackBaseConfig.js
* fix production webpack config
* move more vendor scripts to CDN
> Webpack fix cont.

- README.md
- app.json
- bin/heroku
- bin/setup
- package.json
Now we have **on click deployment**! 🎉 🎉 🎉 🎉
> Config heroku deployment

- app.js
- package.json
Reverts hackmdio/hackmd#231
This will make a mess because we use spaces and breaks to layout.
> Revert "html minify in production environment"

- .editorconfig
- package.json
- public/js/cover.js
- public/js/extra.js
- public/js/htmlExport.js
- public/js/index.js
- public/js/pretty.js
- public/js/slide.js
- public/views/head.ejs
- public/views/index.ejs
- public/views/pretty.ejs
- public/views/slide.ejs
- webpack.config.js
- webpack.production.js
- webpackBaseConfig.js
* Bundle css using webpack
* Bundle css for html export functionality
> Use webpack to bundle stylesheet

- bin/heroku
- lib/models/index.js
As described in https://github.com/hackmdio/hackmd/issues/273#issue-194761291, I've just finished implementation and make it works 😅
> Fix heroku production postgres setting

- app.js
> S3 bucket name

- config.json.example
Ref: https://github.com/sequelize/express-example/blob/master/config/config.json
> Change database config development to sqlite, test to memory

- lib/config.js
> first envs then the config

- locales/ru.json
The previous translation was really bad, I tried hard to understand why this tool will help me share knowledge ABOUT the markdown language. Then I switched to English and realized the real meaning.
Now it's much clearer
> Fixed style in promo text

- webpackBaseConfig.js
- limit CopyWebpackPlugin only copy files that needed
- Hide assets list in webpack build output
> Webpack fixes

- lib/migrations/20150504155329-create-users.js
- lib/migrations/20150508114741-create-notes.js
- lib/migrations/20150515125813-create-temp.js
- lib/migrations/20150702001020-update-to-0_3_1.js
- lib/migrations/20150915153700-change-notes-title-to-text.js
- lib/migrations/20160112220142-note-add-lastchange.js
- lib/migrations/20160420180355-note-add-alias.js
- lib/utils.js
add missing migration, Fixed #366 , hackmdio/docker-hackmd#9
> fix: Add missing migration

- public/views/hackmd/foot.ejs
- public/views/pretty.ejs
- public/views/slide.ejs
- webpackBaseConfig.js
@ jackycute take a look please 😄
> Use abcjs on cdnjs

- public/views/hackmd/body.ejs
- public/views/hackmd/header.ejs
- public/views/pretty.ejs
- public/views/shared/polyfill.ejs
- public/views/slide.ejs
> Fix indent in views, shouldn't mix tabs with spaces

- lib/response.js
- lib/utils.js
- public/views/slide.ejs
> add the ability to set slide theme in slide options

- public/docs/slide-example.md
I wrote this for the my internal hackmd to show off reveal.js
[demo](https://md.redbrick.dcu.ie/p/slide-example)
> add more reveal features to slide demo

- locales/sv.json
Just a small fix for the Swedish translation.
> minor fix for swedish translation

- lib/web/auth/google/index.js
Newbie to this repo, but I don't think `facebook` is a good name prefix here. If any naming dependency is missing, reject it.
> Fix naming typo.

- public/views/index/body.ejs
Changes: 
- Adds green color to new note button for better visibility 
Screenshot:
Fixes: #493
> Adds green color to new note button

- lib/models/user.js
This PR should fix #549 
Since I don't run a private GitLab Instance to test this, it would be nice, to be tested by the community.
This PR is compatible with `0.5.1`.
```
git clone https://github.com/SISheogorath/hackmd-docker
cd hackmd-docker
$EDITOR docker-compose.yml
docker-compose up
```
In the compose file, please uncomment the [build section](https://github.com/SISheogorath/hackmd-docker/blob/master/docker-compose.yml#L21-L23) and change it to the following:
```
build: 
context: .
dockerfile: debian/Dockerfile
args:
- "VERSION=fix/gitlabAvatar"
- "HACKMD_REPOSITORY=https://github.com/SISheogorath/hackmd.git"
```
And add the needed environment variables for the gitlab config to the [environment section](https://github.com/SISheogorath/hackmd-docker/blob/master/docker-compose.yml#L25- …
> Fix broken profile images in GitLab

- lib/models/revision.js
This _has_ to be doublechecked with PostgreSQL! I did not yet test that.
> createdAt DESC with quotation marks did not work with MySQL fixes #565

- public/docs/features.md
Should help to visualize the permission settings.
> Provide table for permissions

- package.json
> Add jsonlint script to ensure all json files are valid

- public/views/hackmd/header.ejs
Fixes : #577 
Hides export section from header if no auth is present
> Hides empty export section

- README.md
- app.json
- lib/config/default.js
- lib/config/environment.js
- lib/config/index.js
- lib/response.js
- public/views/hackmd/header.ejs
Adds a config variable for enabling & disabling PDF exports
Fixes #561
> Adds enable/disable PDF export via config

- public/js/extra.js
Introduced by https://github.com/knsv/mermaid/commit/a5b71455271aef1180eefa1054d751dea1885e3f#diff-67ae90c5144c55348a3cbdb078240454L532
Fixes #600
Extends #607
> Use mermaidAPI in mermaid scope

- public/js/extra.js
> Fix mermaid error handling

- .travis.yml
Hi @SISheogorath, this PR is the one I mention that I need to wait for the other two PRs, which will enable matrix on Travis CI, and then add build, ShellCheck & jsonlint test.
Let me know if there is anything I need to do else, thanks!
> Refactor travis ci config

- locales/en.json
- locales/nl.json
- public/views/hackmd/body.ejs
This pull request fixes a small spelling mistake and adds 2 non-localized sentences to the locale.
> Fix small spelling mistake and add untranslated sentences to locale

- AUTHORS
- CONTRIBUTING.md
- CONTRIBUTORS
- LICENSE
- contribute/developer-certificate-of-origin
- package.json
We [propose a license change, from **MIT** to **AGPL 3.0**](https://hackmd.io/s/r1_4j9_hZ), for the open source project HackMD Community Edition (CE), and ask for your understanding and agreement.
Please leave a comment below the PR saying: 
**“I agree to the change of license from MIT to AGPL on all my past code contribution to the project HackMD. 
Signed-off-by:  Full_name <my_real@mail.address>“**
Thank you again for your contribution to the project and the community.
Please let us know if you have any questions.
> License Change Agreement

- lib/realtime.js
Fix wrong parameters passing order and wrong user object indexing in for each function
> Fix minor typos in realtime

- lib/models/revision.js
> Ignore empty values for revision.

- public/js/extra.js
> Fix image alt not render properly

- app.js
- lib/config/default.js
- lib/config/dockerSecret.js
- lib/config/environment.js
> Fix not passing app key correctly in dropbox config

- locales/de.json
Some improvements for the German translation. Adding missing phrases.
> Extent german translation

- public/views/index/body.ejs
Add CE text on index title to help identify the version of HackMD.
> Add CE text on index title

- public/js/extra.js
Which caused by not matching syntax with double dashes correctly
> Fix task todo might not toggle

- locales/de.json
- locales/en.json
- locales/zh-CN.json
- public/views/index/body.ejs
Some refactoring work for the social media footer.
Open for suggestions. I'm currently not sure of we want to mention them or simply place icons there which are links. This would require less translation work.
> Reorganize social media links and footer

- .travis.yml
- package.json
> Use jq instead of jsonlint

- docs/guides/auth.md
> Fix small typo

- lib/config/environment.js
> Convert  HMD_MINIO_PORT into Number type.

- public/vendor/inlineAttachment/inline-attachment.js
Some minor fixes to the inline-attachment extension for CodeMirror.
Should fix #644
> Some fixes for inline-Attachments in Codemirror

- README.md
- app.js
- lib/config/default.js
- lib/config/environment.js
- lib/config/index.js
- lib/config/oldDefault.js
- lib/csp.js
- lib/models/index.js
- lib/models/note.js
- lib/ot/server.js
- lib/realtime.js
- lib/response.js
- lib/web/auth/dropbox/index.js
- lib/web/auth/email/index.js
- lib/web/auth/facebook/index.js
- lib/web/auth/github/index.js
- lib/web/auth/gitlab/index.js
- lib/web/auth/google/index.js
- lib/web/auth/index.js
- lib/web/auth/ldap/index.js
- lib/web/auth/mattermost/index.js
- lib/web/auth/saml/index.js
- lib/web/auth/twitter/index.js
- lib/web/imageRouter/filesystem.js
- lib/web/imageRouter/index.js
- lib/web/middleware/redirectWithoutTrailingSlashes.js
- lib/web/statusRouter.js
- public/views/hackmd/header.ejs
- public/views/shared/signin-modal.ejs
This refactors the configs a bit to now use camelcase everywhere.
This change should help to clean up the config interface and make it
better understandable.
fixes #315
> Change config to camel case with backwards compatibility

- README.md
- public/docs/release-notes.md
Providing release notes for version 1.1.0-ce
> Update release notes

- public/docs/features.md
Adding some documentation for night mode and upload times. Extend the
contact section for community support.
> Provide feature changes in 1.1.0-ce

- lib/web/auth/saml/index.js
See file changes
"grouptAttribute" in saml auth should be "groupAttribute"
> Fix typo of "grouptAttribute" in saml auth module

- app.js
- lib/config/default.js
- lib/config/environment.js
- public/views/hackmd/header.ejs
first of all we have a security fix where the client secret was exposed.
Also Google drive input was at least broken since 1.1.0-ce and this simply removes the UI elements for now.
Needs a refactoring later.
/cc @ccoenen
> Workaround Google API problems

- app.js
- lib/config/default.js
- lib/config/environment.js
- public/views/hackmd/header.ejs
> Revert "Workaround Google API problems"

- public/css/slide.css
try to solve #831
And try to make it aligned with list items:
> fix(slide): adjust checkbox size

- README.md
- config.json.example
- lib/config/default.js
- lib/config/dockerSecret.js
- lib/config/environment.js
- lib/config/index.js
- lib/web/imageRouter/azure.js
- package.json
Add support for storing images in an Azure Blob Storage container.
> Add Azure Blob Storage support

- public/views/hackmd/head.ejs
- public/views/index/head.ejs
- public/views/pretty.ejs
- public/views/slide.ejs
We don't support it on CDN false instances, but it doesn't hurt to keep
it in for CDN-enabled instances
fixes #841
> Move polyfill to CDN section

- public/css/index.css
- public/css/markdown.css
- public/views/codimd/body.ejs
- public/views/index/body.ejs
We have some issues with night mode and the font color. This should fix
this in the permission table and the delete node modal. As well as some
picture styling.
Fixes #878
> Fix some night mode colors

- public/css/extra.css
- public/vendor/md-toc.js
This replaces the existing iterative implementation of the ToC
generation with an recursive one.
This also solves the problem of skipped headers which causes wrong
leveling of them.
Fixes #816 
also fixes  #502
> Refactor generation of ToC

- lib/csp.js
> Add script src hash for speaker note to CSP directives

- public/js/lib/editor/toolbar.html
Signed-off-by: Alexander Wellbrock <a.wellbrock@mailbox.org>
> Fix some false titles

- lib/history.js
- lib/models/note.js
This adds some error handling as well as previous checks for the need to run LZString to history migration as well as the Note model function
Fixes #891
> Some minor improvements for LZString handling

- README.md
- config.json.example
- lib/config/index.js
- lib/response.js
- public/js/index.js
- public/views/codimd/body.ejs
Apart from the uri versioning, one big change is the snippet visibility post data (visibility_level -> visibility)
Should resolve #887.
Signed-off-by: Cédric Couralet <cedric.couralet@gmail.com>
> Add possibility to choose between version v3 or v4 for the gitlab api.

- README.md
> Add Cloudron as an installation method

- lib/config/index.js
Hey there
just found a small logic mistake and typo  for the gitlab api version check :)
Signed-off-by: Alexander Hesse <alexander.hesse@sandstorm-media.de>
> BUGFIX: wrong version check for gitlab api

- public/js/extra.js
- public/views/codimd/body.ejs
- public/views/codimd/header.ejs
- public/views/index/body.ejs
- public/views/shared/refresh-modal.ejs
The noopener construct protects from some nasty clickjacking attacks. We
can apply them savely to all our links since we don't rely on the
previously used page.
Some more details: https://mathiasbynens.github.io/rel-noopener/
> Add rel="noopener" to target="_blank" links

- lib/config/default.js
- lib/config/environment.js
- lib/config/index.js
- lib/response.js
- lib/web/auth/index.js
- lib/web/auth/openid/index.js
- package.json
- public/views/shared/signin-modal.ejs
With OpenID every OpenID capable provider can provide authentication for
users of a CodiMD instance. This means we have federated
authentication.
> Add OpenID to CodiMD

- package.json
Adding myself as maintainer in `package.json` and change the website URL from https://hackmd.io to https://codimd.org
> Fix maintainer and URL in package.json

- webpack.common.js
Just a small cleanup of the common webpack config.
> Webpack: Cleanup common config

- bin/manage_users
- add an option `reset` to reset user password
- refactored some code in ES6(eliminate var, use template string)
- refactored the way to check arguments
- check type of argv[action] to ensure that is `string` to avoid a pass a boolean email to database
- check type of pass
> add option reset in bin/manage_users

- app.js
- lib/response.js
- public/views/codimd/foot.ejs
- public/views/codimd/head.ejs
- public/views/codimd/header.ejs
- public/views/error.ejs
- public/views/index/body.ejs
- public/views/index/head.ejs
- public/views/pretty.ejs
- public/views/shared/refresh-modal.ejs
- public/views/shared/signin-modal.ejs
- public/views/slide.ejs
things that will be needed on every single page render are now set in app.js. This will make it much easier to introduce new page types (think: admin backend, user profile etc)
> removing global site layout vars from individual routers

- lib/ot/editor-socketio-server.js
Seems like there was some debugging going on some day, this patch should
make sure the right logging is used.
> Fix logging in ot module

- public/docs/features.md
- public/docs/slide-example.md
- public/docs/yaml-metadata.md
Looks like we have a document type slide out there in the wild which is completely undocumented but really awesome.
So let's make it know to the people, so they can make use of it!
> Add documentation for document type

- README.md
- config.json.example
- lib/config/default.js
- lib/config/environment.js
- lib/config/index.js
- lib/logger.js
- package.json
Our log library got a new major version which should be implemented.
That's exactly what this patch does. Implementing the new version of the
logging library.
> Upgrade winston / refactor logging

- .eslintignore
- .eslintrc.js
- README.md
- lib/models/index.js
- lib/models/user.js
- lib/realtime.js
- lib/web/imageRouter/filesystem.js
- package.json
- public/.eslintrc.js
- public/js/history.js
- public/js/index.js
- public/js/lib/editor/index.js
- public/js/lib/editor/ui-elements.js
Most rules degraded to WARN, so we don't go insane. ~~Over time, I'd like to reduce the amount of globals, if possible~~ (globals now only affect the client part of the code). I'd also like to reinstate the defaults instead of overriding as warning. But before we do that, we should probably discuss if standard is still the way to go.
> switching to eslint for code checking

- lib/migrations/20150702001020-update-to-0_3_1.js
- lib/migrations/20160112220142-note-add-lastchange.js
- lib/migrations/20160420180355-note-add-alias.js
- lib/migrations/20160515114000-user-add-tokens.js
- lib/migrations/20160607060246-support-revision.js
- lib/migrations/20160703062241-support-authorship.js
- lib/migrations/20161009040430-support-delete-note.js
- lib/migrations/20161201050312-support-email-signin.js
I think this already happened in the past, i guess is some library version change.
> Fix migration failure due to change on error messages

- lib/config/index.js
972a81aa updated the actual default. This PR reflects that change in the preceding error message.
Fixes #1107.
> Update upload provider error message

- public/js/render.js
- public/views/shared/disqus.ejs
- Fix to sanitize disqus shortnames to remove slashes [Security Issue]
- Fix to escape html comment tag [Security Issue]
> Fix some XSS issues

- public/views/codimd/foot.ejs
- public/views/pretty.ejs
- public/views/slide.ejs
see more at: http://docs.mathjax.org/en/latest/safe-mode.html
> Fix possible MathJax XSS issue [Security Issue]

- locales/fr.json
Signed-off-by: Luclu7 <me@luclu7.fr>
> Corrected a typo

- locales/en.json
- public/views/index/body.ejs
- public/views/shared/signin-modal.ejs
There are some places in our code that made it to be not translated.
This patch fixes some small translation problems and adds some static
strings in templates to translation.
> Add some missing translations

- public/js/extra.js
There is vulnerability inside view rendering that might produce XSS.
Thanks @k1tten for reporting to us 😄
> Fix stored XSS in the graphviz error message rendering [Security Issue]

- package.json
- yarn.lock
Fixed js-sequence-diagram reverse signal problem
> fix: js-sequence-diagram

- lib/config/environment.js
- lib/web/imageRouter/s3.js
Introduce new environment variable `CMD_S3_ENDPOINT` to make the S3 endpoiint URL of the AWS SDK configurable.
> Make AWS S3 endpoint configurable

- lib/migrations/20171009121200-longtext-for-mysql.js
- lib/migrations/20180209120907-longtext-of-authorship.js
- lib/migrations/20180306150303-fix-enum.js
> fix: migration should return promise

- package.json
Signed-off-by: Jenny Danzmayr <mail@evilscientress.at>
> updated flowchart.js to v1.12.0 closing #1225

- package.json
fixes #351 
> https://github.com/hackmdio/CodeMirror/pull/4
> Yank to `*` or `+` register would copy text to clipboard
> 
> ![codemirror-yank-to-clipboard](https://user-images.githubusercontent.com/4230968/59548958-96cf4100-8f88-11e9-9c21-60c2ddd5a957.gif)
> Update codemirror to 5.46.2

- lib/web/middleware/tooBusy.js
- package.json
- public/js/extra.js
- public/views/codimd/foot.ejs
- public/views/pretty.ejs
- public/views/slide.ejs
to avoid XSS inside the svg tag
see issue #1233
> Upgrade mermaid to 8.2.3

- lib/realtime.js
assigning random animal name to guest
resolved #1244
> feat: change guest random nameing to chance.animal()

- lib/history.js
- lib/response.js
fix circular dependencies cause by PR #1179
>  fix: history api failed cause by circular dependency

- package.json
- webpack.common.js
related to #262 
Use [emoji-data](https://github.com/iamcal/emoji-data) to provide emoji sets (apple-flavored). It's more completed and standard compliance.
> Experimental support for customized emojify version

- package.json
- public/docs/features.md
- public/js/extra.js
> Support markdown-it-ruby syntax

- public/js/extra.js
- public/js/lib/syncscroll.js
fixes #1265 
fixes hackmdio/hackmd-io-issues#109
> Support empty spoiler container syntax

- public/js/extra.js
- public/views/codimd/foot.ejs
- public/views/index/foot.ejs
- public/views/index/head.ejs
- public/views/pretty.ejs
- public/views/slide.ejs
- webpack.common.js
- yarn.lock
- fixes #1292 : viz.js@2 api changes
- fixes #1284
> Fix dependencies upgrade issues

- lib/config/index.js
- lib/response.js
related to #1302 
Set [markdown-pdf](https://www.npmjs.com/package/markdown-pdf)'s option to provide syntax highlight on PDF output.
I worked with @betsu6419 and @simkaren .
Realize syntax highlight on PDF same to View.
> Feature/syntax hilight on PDF

- public/js/index.js
- public/js/lib/editor/table-editor.js
and avoid add/remove keymap on every updateActiveState
> fix: table editor key map might conflict with textcomplete keymap

- config.json.example
- lib/config/default.js
- lib/config/environment.js
- lib/models/user.js
- lib/web/auth/github/index.js
resolve #1269
config example
```json
{
"production": {
"github": {
"clientID": "**************",
"clientSecret": "************************************",
"enterpriseURL": "https://github-internal.example.com"
}
}
}
```
> support to login with github enterprise

- package.json
- public/js/lib/editor/markdown-lint/index.js
- public/js/url.js
- webpack.common.js
- yarn.lock
> Update markdownlint & webpack bundling

- README.md
> Add line break to README migration section

- .buildpacks
- scalingo.json
Closes #1359 
[![Deploy to Scalingo](https://cdn.scalingo.com/deploy/button.svg)](https://my.scalingo.com/deploy?source=https://github.com/hackmdio/codimd)
Here is the code for this one-click deploy button:
```
[![Deploy to Scalingo](https://cdn.scalingo.com/deploy/button.svg)](https://my.scalingo.com/deploy?source=https://github.com/hackmdio/codimd)
```
To deploy with a custom branch, for example with `develop`, add `#` followed by the name of the branch:
`https://my.scalingo.com/deploy?source=https://github.com/hackmdio/codimd#develop`
> Added Scalingo compatible deployment

- lib/web/imageRouter/minio.js
- package.json
- yarn.lock
> feat(imageUpload): upgrade minio version to 7.0.12

- public/views/includes/header.ejs
- public/views/includes/scripts.ejs
> Fix urlpath in webpack build

- package.json
> chore: update maintainers list

- public/views/codimd/header.ejs
This PR revive PR #665, I think it makes sense.
> fix: flip the view and edit header buttons

- app.js
> Enable version check only in NODE_ENV production

- app.js
- lib/auth/email/index.js
- lib/auth/ldap/index.js
- lib/history/index.js
- lib/imageRouter/index.js
- lib/middleware/checkURIValid.js
- lib/middleware/tooBusy.js
- lib/note/index.js
- lib/note/noteActions.js
- lib/response.js
- lib/user/index.js
1. fix server throw TypeError when user not sign-in
2. fix issue when shortId not found on publish link
> Fix some issues after code refactoring

- package-lock.json
- package.json
- public/css/mermaid.css
- public/views/codimd/foot.ejs
- public/views/pretty.ejs
- public/views/slide.ejs
Upgrade mermaid from 8.2.3 to 8.4.8
From mermaid:
- Fix for infinite loop on parsing Date https://github.com/mermaid-js/mermaid/issues/1060
- Support `[(Database)]` shape in Flow chart
---
- Fix to solve a style conflict of label class in mermaid and bootstrap
before:
after:
> Feature/upgrade mermaid 8.4.8

- lib/note/noteActions.js
> Fix server crash when download pdf twice

- lib/auth/oauth2/index.js
- lib/auth/oauth2/strategy.js
- lib/config/default.js
- lib/config/environment.js
- test/auth/oauth2/strategy.test.js
> fix server crash when use oauth2 provider with email not exists

- lib/csp.js
- package-lock.json
- package.json
- public/css/extra.css
- public/css/markdown.css
- public/css/slide.css
- public/js/extra.js
- public/js/index.js
- public/views/codimd/foot.ejs
- public/views/codimd/head.ejs
- public/views/pretty.ejs
- public/views/slide.ejs
- webpack.common.js
resolve #592 
~~~md
```geo
longitude,latitude,zoomFactor
```
or
```geo
Address
```
~~~
We can provide more customization through YAML-like config in the future:
```yaml
location:
lng: 123.123123
lat: 23.567567
description: popover description
map_type: osm # or google maps
```
> Support embedding geolocation data

- lib/auth/google/index.js
- lib/config/default.js
- lib/config/environment.js
fix #1383
support customize hostedName parameter in google OAuth2.0 provider
> Support hostedName in google OAuth provider

- locales/en.json
- locales/zh-TW.json
Update missing tranlsation string for pandoc
> Update pandoc i18n

- package-lock.json
- package.json
Support plantuml language mode:
> Bump codemirror version to 5.49.5

- lib/config/dockerSecret.js
Add some missing config in docker secret.
> Fix not all config in docker secret

- lib/imageRouter/minio.js
This should fix #1452
Signed-off-by: Kishan Mehta <kishan@scrapinghub.com>
> Add correct path for minio

- package-lock.json
- package.json
The code in `@hackmd/imgur` has some issue that doesn't require `q` properly
> fix: cannot upload image via imgur

- lib/note/index.js
> return errorForbidden when anonymous user tries to create freeUrl pad

- app.js
- lib/metrics.js
- lib/routes.js
- lib/status/index.js
- package-lock.json
- package.json
- public/js/lib/common/metrics.ejs
#1466 
1. **/metrics/router** : exporting node.js/express Prometheus metrics by
[prometheus-api-metrics](https://www.npmjs.com/package/prometheus-api-metrics)
2. **/metrics/codimd** : exporting codimd realtime status (/status) as
Prometheus metrics
[12214](https://grafana.com/grafana/dashboards/12214)
> Exporting metrics for node.js, express, router, and codimd realtime status.

- deployments/build.sh
- upgrade runtime image to support phantomjs
> fix: photomjs dep.

- public/css/cover.css
- public/views/shared/signin-modal.ejs
avoid to use btn-social, some AD block will delete
the DOM with btn-social class.
fixed #1491
> fix: replace btn-social with btn-login-method

- public/js/extra.js
- public/js/lib/renderer/lightbox/index.js
- public/js/lib/renderer/lightbox/lightbox.css
- public/js/lib/syncscroll.js
- zoom scale transform origin(https://stackoverflow.com/a/15296290https://stackoverflow.com/a/15296290)
- https://www.sitepoint.com/community/t/javascript-css3-mousewheel-zoom-origin-problem/221456/4
- touch support
- fit image to screen if image is oversize
> Simple image lightbox

- public/docs/features.md
- public/js/extra.js
- public/js/lib/renderer/fretboard/css/i.css
- public/js/lib/renderer/fretboard/fretboard.js
Make fretboard rendered results fit more with CodiMD.
> Fretboard improvement

- public/css/index.css
Fix #1539
Active buttons should be treated equally.
> Fix ui-edit and ui-both buttons in night mode

- package-lock.json
- public/js/lib/renderer/fretboard/fretboard.js
- public/js/lib/renderer/lightbox/index.js
> Fix xss issue for image lightbox

- package-lock.json
- package.json
- public/views/codimd/foot.ejs
- public/views/pretty.ejs
- public/views/slide.ejs
> Bump mermaid version

- package-lock.json
- package.json
> Release 2.3.2

- package-lock.json
- package.json
- public/js/lib/editor/index.js
- public/js/lib/editor/markdown-lint/index.js
- public/markdown-lint/css/lint.css
- webpack.common.js
related to https://github.com/hackmdio/hackmd-io-issues/issues/128
- https://github.com/DavidAnson/vscode-markdownlint/blob/b596db721a7519bf87235d964c48c45f1078fab5/extension.js#L498-L551
> Autofix linter errors

- lib/note/index.js
> Use encoded noteId when calling updateHistory

- lib/models/note.js
> Fix parseNoteId bug

- lib/user/index.js
> Avoid append zero suffix on exporting user data

- lib/imageRouter/s3.js
Fix #1572 which not passing config to S3 client properly
ref issue: https://github.com/aws/aws-sdk-js-v3/issues/1396
> Fix S3 client config passing for image upload

- public/js/mathjax-config-extra.js
> Add TeX mhchem extensions for MathJax

- package-lock.json
- package.json
Upgrade flowchart.js to version 1.15.0
> Upgrade flowchart.js to version 1.15.0

- package-lock.json
- package.json
- public/views/codimd/foot.ejs
- public/views/pretty.ejs
- public/views/slide.ejs
to avoid mermaid prototype pollution https://github.com/mermaid-js/mermaid/issues/1940
found by https://github.com/RenwaX23/X/blob/master/ctf/pwn2win_hackus.md
cc @RenwaX23
> Upgrade mermaid to version 8.10.2 to avoid prototype pollution

- deployments/Dockerfile
- deployments/build.sh
Need to use the runtime and buildpack image in [hackmdio/docker-buildpack#3](https://github.com/hackmdio/docker-buildpack/pull/3)
I really hope that you can publish an arm64 build in dockerhub.
> Add arm64 docker image build.

- public/js/history.js
> fix: should not clear guest history when guest pin note

- lib/imageRouter/s3.js
fixes: https://github.com/hackmdio/codimd/issues/1761
> Fix: s3 api supported multiple cloud providers. fixes: https://github.com/hackmdio/codimd/issues/1761

- README.md
> Update README.md to remove IE from supporting list

- public/js/extra.js
access `videoid` directly has potential XSS risk
> potential XSS in vimeo embed

- package-lock.json
- package.json
> chore: bump meta-marked to 0.5.0

- public/views/shared/ga.ejs
> feat: Migrate to gtag and support GA4

- public/views/index/body.ejs
to avoid overlapping other buttons, affected by #1695
fixes #1778, #1783
> Fix history page nav

- package-lock.json
- package.json
Refer to https://github.com/hackmdio/pandoc.js/pull/15
> chore: bump pandocjs version

- package-lock.json
- package.json
v0.2.0 was not bundled correctly
> chore: @hackmd/pandoc.js to 0.2.1

- lib/note/noteActions.js
- package-lock.json
- package.json
- chore: bump @hackmd/pandoc to 0.3.4
- fix: only allow string type exportType paramter
> Address pandoc related issues

- .github/workflows/push-image.yml
Now the docker image is build with multi-platform docker
> Build docker image using github actions cont

- public/views/codimd/head.ejs
Support the integration of Codeium chrome chrome extension
https://github.com/Exafunction/codeium-chrome
https://github.com/hackmdio/codimd/assets/4230968/a6ef32b2-b3a5-4468-be2f-1ae8f7de9c11
> Support codeium chrome extension

- README.md
> typo: opened source -> open sourced

- public/js/render.js
> fix: exclude name attribute from iframe filterXSS allowlist

- package-lock.json
- public/.eslintrc.js
Enhance the ESLint configuration to support ES6 features and specify parser options for ECMAScript 2018.
> Update ESLint configuration for ES6 support

- .github/workflows/build.yml
- package-lock.json
- package.json
Mark extraneous dependencies in package-lock.json as dev and optional, and update the mermaid dependency to version 11.5.0.
> Upgrade mermaid to latest version

- public/views/codimd/foot.ejs
- public/views/pretty.ejs
- public/views/slide.ejs
Upgrade abcjs to version 6.4.4 and mermaid.js to version 11.5.0 to ensure compatibility and access to the latest features.
continue #1891 and #1894
> Update dependencies for abcjs and mermaid.js
